/* English for the Korean strings this plugin is written in.

   The Korean text is the key: see i18n.js for why. A string that is not here
   still reads correctly in Korean, so this table can be filled in over time
   without any moment where the panel is broken.

   Generated; edit the table rather than this file by hand. */
(function (root) {
  'use strict';
  const en = {
 "\n조회 실패 {0}": "\nLookup failed {0}",
 " · DOI 없음 {0}": " · no DOI {0}",
 " · {0}편 조회 실패": " · {0} failed",
 " · {0}편은 기록 없음": " · {0} with no record",
 " · 기관 {0}곳": " · {0} institutions",
 " · 다른 논문 {0}": " · different papers {0}",
 " · 미판별 {0}": " · unjudged {0}",
 " · 연결 없음 {0}": " · unconnected {0}",
 " · 예: {0}{1}": " · e.g. {0}{1}",
 " · 인용 목록 없음 {0}": " · no reference list {0}",
 " · 중복 {0}": " · duplicates {0}",
 " · 판단 불가 {0}": " · undecided {0}",
 " · 확인 필요": " · needs checking",
 " 기본값 복원": " restore defaults",
 " 기본값을 적용하는 중…": " restoring defaults…",
 " 더 보기 ·": " more · ",
 " 더 보기 · ": " more · ",
 " 선택": " select",
 " 적용": " apply",
 " 필터 해제": " clear filter",
 "(제목 없음)": "(untitled)",
 "1저자 {0} · {1}": "First author {0} · {1}",
 "4805초": "4805 s",
 "AI 읽기 메모 제안 사용": "Enable AI reading-note suggestions",
 "AI 태그 제안 사용": "Enable AI tag suggestions",
 "API 키": "API key",
 "Custom 패널 CSS": "Custom panel CSS",
 "DOI 확인": "Check DOI",
 "IF 열 사용": "Enable the IF column",
 "OpenAlex에서 보기": "View on OpenAlex",
 "PDF 첨부 버전 전환 사용": "Enable switching between PDF versions",
 "PDF 테마": "PDF theme",
 "PDF만": "PDF only",
 "Style Custom 설정": "Style Custom settings",
 "Tags / 제목 태그": "Tags / title tags",
 "{0} · {1}개 문헌{2}": "{0} · {1} items{2}",
 "{0} · 확인 {1}": "{0} · checked {1}",
 "{0}–{1} / {2}개": "{0}–{1} of {2}",
 "{0}개 문헌 선택{1}": "{0} items selected{1}",
 "{0}개 설정 검색됨": "{0} settings found",
 "{0}분": "{0}m",
 "{0}시간 {1}분": "{0}h {1}m",
 "{0}점 이상": "{0} and above",
 "{0}종 조회 실패": "{0} journals failed",
 "가 없습니다.": " is missing.",
 "가져오지 못했습니다.": "Could not import.",
 "간격 넓게": "Comfortable",
 "간격 좁게": "Compact",
 "값을 읽지 못했습니다: ": "Could not read the value: ",
 "강조 색상": "Accent colour",
 "개": "",
 "개 남음": " left",
 "개 문헌": " items",
 "개 적용": " applied",
 "검색": "Search",
 "검색 결과 전체 선택": "Select all results",
 "검색 지우기": "Clear search",
 "검색된 기능": "Matching features",
 "게재됨 →": "Published →",
 "공개 접근 ({0})": "Open access ({0})",
 "공개 접근본이 없습니다.": "No open-access copy.",
 "공통 저자": "Shared authors",
 "공통 태그": "Shared tags",
 "관계 그래프": "Citation map",
 "관계·태그·저자 그래프 사용": "Enable the citation, tag and author graphs",
 "관련 논문": "Related papers",
 "관련 문헌": "Related",
 "관련 문헌으로 연결": "Link as related",
 "관심 저자 새 논문": "New work by watched authors",
 "교신저자 {0} · {1}": "Corresponding {0} · {1}",
 "교신저자가 {0}명입니다.": "There are {0} corresponding authors.",
 "국제 공동연구": "International collaboration",
 "그래프 최대 문헌 수": "Maximum items in the graph",
 "기능 바로 찾기": "Jump to a feature",
 "기능 찾기": "Find a feature",
 "기능 찾기 · ⌘/Ctrl K": "Find a feature · ⌘/Ctrl K",
 "기록·표시 갱신 간격 (ms)": "Record and refresh interval (ms)",
 "기록이 없어도 0초 표시": "Show 0s even with no record",
 "기본 Custom 열 표시": "Show the default custom columns",
 "기본 순서": "Default order",
 "기존 태그 경로": "Existing tag path",
 "긴 제목 호버 스크롤": "Scroll long titles on hover",
 "꺼짐": "off",
 "나중에": "Later",
 "날짜 표시": "Date display",
 "내 논문 {0}편이 인용합니다": "{0} of my papers cite it",
 "내용 복사": "Copy",
 "노트": "Notes",
 "노트 검색·생성·편집 사용": "Enable note search, creation and editing",
 "노트 편집": "Edit note",
 "논문 비교": "Compare",
 "누적 읽기 ": "Total reading ",
 "다른 논문": "Different paper",
 "다른 논문 {0}개": "{0} different paper",
 "다른논문×{0}": "other×{0}",
 "다음 페이지": "Next page",
 "닫기": "Close",
 "대기": "Waiting",
 "도구": "Tools",
 "독립 세로 탭 목록 사용": "Enable the standalone vertical tab list",
 "라이브러리": "Library",
 "라이브러리 저널 지표 채우기": "Fill in journal metrics for the library",
 "리더 사이드바 토글 사용": "Enable the reader sidebar toggle",
 "리더 사이드바 표시": "Show reader sidebar",
 "리더·주석": "Reader and annotations",
 "마지막 연도": "To year",
 "먼저 문헌을 선택하세요.": "Select an item first.",
 "메뉴·디자인": "Menus and design",
 "메모 저장": "Save note",
 "메모 주석 표시": "Show notes",
 "메모를 저장했습니다.": "Note saved.",
 "몇 시간·며칠 전": "Hours or days ago",
 "모델 이름": "Model name",
 "모든 별점": "Any rating",
 "모든 유형": "All types",
 "모든 일반 태그": "All ordinary tags",
 "모든 읽기 상태": "Any status",
 "모든 파일": "All files",
 "목록에서 값을 선택하세요.": "Choose a value from the list.",
 "목록의 값을 선택하세요.": "Choose a value from the list.",
 "무활동 제외 기준 (초)": "Idle threshold (seconds)",
 "문헌 관계 그래프": "Item relationship graph",
 "문헌 노트 편집": "Edit the note",
 "문헌 상세 필터": "Detailed filters",
 "문헌 유형 필터": "Item type",
 "문헌 정렬": "Sort",
 "문헌 페이지 범위": "Page range",
 "문헌을 먼저 선택하세요.": "Select an item first.",
 "문헌을 읽는 중…": "Loading items…",
 "문헌을 찾지 못했습니다.": "The item was not found.",
 "문헌을 하나 선택하세요.": "Select exactly one item.",
 "밑줄 표시": "Show underlines",
 "밝게": "Light",
 "밝은 PDF": "Light PDF",
 "방금": "just now",
 "버전 ": "Version ",
 "번역 · AI": "Translate · AI",
 "번역·AI": "Translation and AI",
 "별점": "Rating",
 "별점 {0}/5": "Rating {0}/5",
 "별점 높은 순": "Highest rated",
 "별점 열 표시": "Show the Rating column",
 "별점 지우기": "Clear rating",
 "보드 이름을 입력하세요.": "Enter a board name.",
 "보유 문헌": "Library",
 "보충자료 {0}개": "{0} supplementary",
 "보충자료 — 클릭하면 열립니다": "Supplementary — click to open",
 "보충자료 내려받기": "Download supplementary",
 "보충자료 표시 해제": "Unmark as supplementary",
 "보충자료가 없는 논문입니다": "This paper has no supplementary material",
 "본문 {0}개": "{0} article",
 "본문 발췌 표시 글자 수": "Excerpt length",
 "분 전": "m ago",
 "뷰 그룹": "View groups",
 "뷰·작업 패널": "Views and panels",
 "비교표 한 페이지 문헌 수": "Items per comparison page",
 "빈 응답": "Empty response",
 "사용자 PDF 글자": "Custom PDF text",
 "사용자 PDF 배경": "Custom PDF background",
 "사용자 PDF 테마 적용": "Apply custom PDF theme",
 "사용자 색상": "Custom colours",
 "사이드바·탭": "Sidebar and tabs",
 "사진 출처: {0}": "Photo: {0}",
 "상세 필터": "Filters",
 "상위": "High",
 "상태": "Status",
 "새 노트 내용": "New note",
 "새 노트 저장": "Save the note",
 "새 태그 경로": "New tag path",
 "새로고침": "Refresh",
 "색 지우기": "Clear colour",
 "색 표시": "Show colour",
 "색상 이름 저장": "Save colour name",
 "색상 태그 표시 사용": "Enable coloured tags",
 "색상이 지정된 태그": "Tags with a colour",
 "선택": "Select",
 "선택 문헌 인용 수 조회": "Look up citations for the selection",
 "선택 문헌 태그 이름 변경": "Rename tag on selection",
 "선택 문헌끼리 연결 해제": "Unlink selected",
 "선택 문헌에 태그 추가": "Add tags to selection",
 "선택 문헌에서 태그 제거": "Remove tags from selection",
 "선택 저널 공식 IF 확인": "Check the official IF for the selected journal",
 "선택 저널 등급 조회": "Look up the rank for the selected journal",
 "선택 주석 병합": "Merge selected",
 "선택 주석 병합 사용": "Enable merging annotations",
 "선택 주석 색 바꾸기": "Recolour selected",
 "선택 주석 색상 변경": "Recolour selected annotations",
 "선택 해제": "Clear selection",
 "선택 해제 ({0})": "Clear selection ({0})",
 "선택: ": "Selected: ",
 "선택한 문헌": "Selected items",
 "선택한 문헌 ": "Selected ",
 "선택한 문헌 없음": "No item selected",
 "선택한 문헌 인용 수 새로고침": "Refresh citations for the selection",
 "선택한 문헌에 새 노트 작성": "Add a note to the selection",
 "선택한 파일을 보충자료로 표시": "Mark the selected files as supplementary",
 "설정 다시 읽기": "Reload settings",
 "설정 문자열이 너무 깁니다.": "That setting is too long.",
 "설정 분류": "Category",
 "설정 이름·설명 검색": "Search settings",
 "설정에서 이 기능을 켜세요.": "Turn this on in the settings.",
 "설정을 불러오는 중…": "Loading settings…",
 "설정을 불러왔습니다.": "Settings loaded.",
 "설정을 열지 못했습니다: ": "Could not open settings: ",
 "세로 탭 목록 표시": "Show vertical tab list",
 "세피아": "Sepia",
 "세피아 PDF": "Sepia PDF",
 "숫자를 입력하세요.": "Enter a number.",
 "스크롤 속도 (px/s)": "Scroll speed (px/s)",
 "스크롤 시작 대기 (ms)": "Delay before scrolling (ms)",
 "스타일 편집": "Style editor",
 "스타일 편집 / 문헌 제목": "Style editor / item title",
 "시간 전": "h ago",
 "시작 연도": "From year",
 "실행하는 중…": "Running…",
 "실행하지 못했습니다: ": "Could not run: ",
 "실행했습니다.": "Done.",
 "아직 적용하지 않았습니다.": "Not applied yet.",
 "안 읽은 제목 굵게": "Bold unread titles",
 "안 읽음": "unread",
 "앱 밝게/어둡게 전환": "Toggle light/dark",
 "앱 밝게·어둡게 전환 사용": "Enable light/dark toggle",
 "어두운 PDF": "Dark PDF",
 "어둡게": "Dark",
 "여백 위치": "Margin side",
 "여백 주석 글자 크기": "Margin font size",
 "여백 주석 너비 (px)": "Margin width (px)",
 "여백 주석 설정 적용": "Apply margin settings",
 "여백 주석 최대 글자 수": "Margin text limit",
 "여백 주석 표시": "Show margin annotations",
 "역링크": "Backlinks",
 "역링크 기능이 꺼져 있습니다.": "Backlinks are turned off.",
 "연구 작업 패널": "Research panel",
 "연구 작업 패널 열기": "Open the research panel",
 "연락 이메일 (선택)": "Contact e-mail (optional)",
 "열 표시": "Columns",
 "열기": "Open",
 "열을 등록하지 못했습니다: ": "Could not register the column: ",
 "예: 주석, 비교, 탭…": "e.g. annotations, compare, tabs…",
 "오른쪽": "Right",
 "올바른 태그 목록이 아닙니다.": "That is not a valid tag list.",
 "옮길 것이 없었습니다.": "There was nothing to move.",
 "완료": "done",
 "왼쪽": "Left",
 "요청이 중지되었습니다.": "The request was stopped.",
 "워크벤치": "Workbench",
 "워크벤치 → 스타일 편집": "Workbench → Style editor",
 "워크벤치 → 중첩 태그": "Workbench → Nested tags",
 "워크벤치 → 최근 문헌": "Workbench → Recent",
 "워크벤치 → 컬렉션": "Workbench → Collections",
 "원래 테마 유지": "Keep the original",
 "유형": "Type",
 "이 분류 기본값 복원": "Restore defaults for this category",
 "이미지 주석 표시": "Show image annotations",
 "이전 페이지": "Previous page",
 "인용 관계": "Citations",
 "인용 관계 그래프": "Citation map",
 "인용 많은 순": "Most cited",
 "인용 목록 {0}/{1}": "References {0}/{1}",
 "인용 목록 없음": "No reference list",
 "인용 목록·소속": "References and affiliations",
 "인용 수": "Citations",
 "인용 수 열·자동 조회 사용": "Enable the Citations column and automatic lookup",
 "인용 수 조회 중": "Looking up citations",
 "인용 수 조회 중지": "Stop looking up citations",
 "인용 수·IF": "Citations and IF",
 "인용 조회: ": "Citation lookup: ",
 "인용 텍스트 표시": "Show quoted text",
 "인용…": "Cite…",
 "일 전": "d ago",
 "일반": "Other",
 "일치하는 기능이 없습니다.": "No feature matches.",
 "읽기": "Reading",
 "읽기 기록": "Reading history",
 "읽기 기록 ": "Reading history ",
 "읽기 메모": "Reading note",
 "읽기 메모 열 사용": "Enable the Reading note column",
 "읽기 메모 제안": "Suggest reading note",
 "읽기 메모 지시문": "Reading note prompt",
 "읽기 상태 열 표시": "Show the Status column",
 "읽기 상태 필터": "Reading status",
 "읽기 시간 표시 형식": "Reading-time format",
 "읽기 시간·상태 연동 사용": "Link reading time to reading status",
 "읽기 시간순": "Most read",
 "읽기 진행": "Reading progress",
 "읽기 진행 → 색상 이름": "Reading → colour names",
 "읽는 문헌의 수정일 갱신": "Update Modified while reading",
 "읽는 중": "reading",
 "읽은 시간": "Time read",
 "읽음": "read",
 "읽음·안 읽음 제목 구분 사용": "Distinguish read and unread titles",
 "자세히": "Details",
 "작업 메뉴 표시·숨김 사용": "Enable showing and hiding the action menu",
 "작업 종류": "Action",
 "작업 패널 검색": "Search the panel",
 "작업 패널 닫기": "Close the panel",
 "저널 등급 태그·조회 사용": "Enable journal-rank tags and lookup",
 "저널 영향력 지수": "Journal impact factor",
 "저널 정보가 없습니다.": "No journal information.",
 "저널 지표": "Journal metrics",
 "저널·발행처 열 사용": "Enable the Journal and Publisher columns",
 "저자 추적": "Authors",
 "저자·기여자 열 사용": "Enable the Creators column",
 "저장 위치: ": "Stored at: ",
 "저장된 날짜": "Stored date",
 "저장한 노트 열기": "Open the saved note",
 "적용": "Apply",
 "적용 중인 필터": "Active filters",
 "적용하는 중…": "Applying…",
 "적용하지 못했습니다: ": "Could not apply: ",
 "적용했습니다.": "Applied.",
 "전체 내용 보기": "Show the whole thing",
 "접두사와 일치하는 태그": "Tags matching a prefix",
 "정리": "Organise",
 "정리할 별 태그가 없습니다.": "There are no star tags to tidy.",
 "제목 앞 별 태그 정리": "Tidy star tags in titles",
 "제목 없음": "Untitled",
 "제목 옆 최대 태그 수": "Maximum tags beside the title",
 "제목 옆 태그 표시": "Show tags beside the title",
 "제목 히트맵·태그·강조 사용": "Enable title heat maps, tags and highlighting",
 "제목·저자·태그 검색": "Search titles, authors and tags",
 "제목순": "By title",
 "제목에 읽기 히트맵 표시": "Show a reading heat map on titles",
 "조회 오류 재시도 간격 (분)": "Retry interval after a failed lookup (minutes)",
 "조회 중": "Looking up",
 "종류 미판별 첨부 {0}편": "{0} with unjudged attachments",
 "주석": "Annotations",
 "주석 메모 표시": "Show annotation comments",
 "주석 색상 이름 사용": "Enable annotation colour names",
 "주석 색상·팔레트 사용": "Enable annotation colours and palettes",
 "주석 원문 열기": "Open the annotation",
 "주석 위치 분포": "Where the annotations are",
 "주석 팔레트 삭제": "Delete palette",
 "주석 팔레트 저장": "Save palette",
 "주석 팔레트 적용": "Apply palette",
 "주석 팔레트를 선택하세요.": "Choose an annotation palette.",
 "주석이 아닙니다.": "That is not an annotation.",
 "준비": "Ready",
 "중복": "Duplicate",
 "중복 {0}개": "{0} duplicate",
 "중복 ×{0}": "dup ×{0}",
 "중복×{0}": "dup×{0}",
 "중상위": "Upper",
 "중위": "Mid",
 "중지했습니다.": "Stopped.",
 "중첩 태그": "Nested tags",
 "중첩 태그 탐색 사용": "Enable nested tag browsing",
 "지금 채우기": "Fill now",
 "지표 없는 저널 {0}종": "{0} journals with no metric",
 "지표 출처 미확인": "Metric source unverified",
 "참/거짓 값을 선택하세요.": "Choose true or false.",
 "참고문헌 {0}건": "{0} references",
 "참조 노트": "Linked notes",
 "참조 노트 보기": "Show linked notes",
 "찾을 기능 이름": "Feature name",
 "처음 펼칠 노트·주석 수": "Notes and annotations shown first",
 "철회 여부 미확인 {0}편": "{0} unchecked for retraction",
 "철회·공개접근 신호": "Retraction and open-access signals",
 "첨부 미리보기": "Attachments",
 "첨부 미리보기 사용": "Enable attachment preview",
 "첨부파일 없음": "No attachment",
 "첨부파일 종류": "Attachment kinds",
 "첨부파일을 선택하세요.": "Select an attachment.",
 "초": "s",
 "초록 요약": "Summarise abstract",
 "초록 요약 사용": "Enable abstract summaries",
 "초록이 없습니다.": "No abstract.",
 "최근 문헌": "Recent",
 "최근 문헌 사용": "Enable Recent items",
 "최상위": "Top",
 "최소 별점": "Minimum rating",
 "최신 발행순": "Newest first",
 "추가 필드 열": "Extra field columns",
 "추가일·수정일 열 사용": "Enable Added and Modified columns",
 "추가할 태그": "Tags to add",
 "축소": "Zoom out",
 "출력 언어": "Output language",
 "캔버스": "Canvas",
 "커스텀 열로 전환": "Switch to custom columns",
 "컬렉션": "Collections",
 "컬렉션 문헌 수 사용": "Enable collection counts",
 "컬렉션 즐겨찾기 사용": "Enable collection favourites",
 "켜짐": "on",
 "클립보드에 복사했습니다.": "Copied to the clipboard.",
 "탐색": "Explore",
 "태그": "Tags",
 "태그 열 표시 대상": "Which tags the column shows",
 "태그 제안": "Suggest tags",
 "태그 제안 지시문": "Tag suggestion prompt",
 "태그 필터 해제": "Clear tag filter",
 "태그로 남은 평점이 없습니다.": "No ratings are left as tags.",
 "탭 관리": "Tabs",
 "탭 그룹 이름": "Tab group name",
 "탭 활동 시 수정일 갱신 사용": "Update Modified when a tab is used",
 "텍스트 주석 표시": "Show text annotations",
 "텍스트 태그 접두사": "Text tag prefix",
 "텍스트 태그·태그 수 사용": "Enable text tags and tag counts",
 "패널 CSS 편집 사용": "Enable panel CSS editing",
 "패널 글자 크기": "Panel font size",
 "펜 주석 표시": "Show ink annotations",
 "표시 범위": "Scope",
 "필터 초기화": "Reset filters",
 "하위 태그도 변경": "Rename child tags too",
 "하이라이트 표시": "Show highlights",
 "한 페이지 문헌 수": "Items per page",
 "항목 아이콘으로 유형 필터": "Filter by type from the item icon",
 "항목 유형 빠른 필터 사용": "Enable the item-type quick filter",
 "현재 동작": "Current behaviour",
 "현재 동작 상태": "Current state",
 "현재 상태를 확인하는 중…": "Checking the current state…",
 "현재 선택 가져오기": "Take the current selection",
 "현재 선택 문헌 누적 읽기": "Total reading time for the selection",
 "현재 컬렉션": "Current collection",
 "현재 컬렉션과 하위 컬렉션": "Current collection and its subcollections",
 "현재 페이지 선택": "Select this page",
 "현재 페이지 선택 해제": "Deselect this page",
 "화면 밀도": "Density",
 "화면 밀도 전환": "Toggle density",
 "확대": "Zoom in",
 "활성 PDF 읽기 시간 기록": "Record reading time for the active PDF"
};
  const api = {en};
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.CustomStyleStrings = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
