/* English for the Korean strings this plugin is written in.

   The Korean text is the key: see i18n.js for why. A string that is not here
   still reads correctly in Korean, so this table can be filled in over time
   without any moment where the panel is broken.

   Generated; edit the table rather than this file by hand. */
(function (root) {
  'use strict';
  const en = {
 "\n{0}개는 색인을 만든 뒤에도 본문을 읽지 못했습니다(스캔 PDF일 수 있습니다).": "\n{0} still had no readable text after indexing (they may be scanned PDFs).",
 "\n대상 문헌을 찾지 못한 노트 {0}개": "\n{0} notes whose item could not be found",
 "\n본문이 없던 {0}개는 Zotero가 먼저 본문을 읽어 두었습니다.": "\nZotero read the text of {0} of them first, because it had none.",
 "\n조회 실패 {0}": "\nLookup failed {0}",
 "  그중 {0}편은 철회 여부만 확인했습니다(공개접근 정보는 한도 복구 후 자동으로 채웁니다).": "  {0} of them were checked for retraction only (open-access information fills in by itself once the allowance returns).",
 " · 2년 평균 피인용 ": " · 2-year mean citations ",
 " · DOI 없음 {0}": " · no DOI {0}",
 " · OpenAlex에 없음 {0}": " · not in OpenAlex {0}",
 " · {0}편 조회 실패": " · {0} failed",
 " · {0}편은 기록 없음": " · {0} with no record",
 " · 기관 h-index {0}": " · institution h-index {0}",
 " · 기관 {0} (h-index 있음 {1})": " · institutions {0} (with an h-index {1})",
 " · 기관 {0}곳": " · {0} institutions",
 " · 다른 논문 {0}": " · different papers {0}",
 " · 다른 논문 {0} · 첨부 없음 {1}": " · different papers {0} · no attachment {1}",
 " · 마지막 확인 {0}": " · last checked {0}",
 " · 미판별 {0}": " · unjudged {0}",
 " · 보충자료만 {0} (원논문 찾음 {1})": " · supplementary only {0} (original found {1})",
 " · 보충자료만 {0} · 첨부 없음 {1}": " · supplementary only {0} · no attachment {1}",
 " · 빈 항목은 휴지통으로": " · empty ones go to the trash",
 " · 새 논문 {0}편": " · {0} new",
 " · 새 논문 {0}편 · {1}명": " · {0} new papers · {1} people",
 " · 실패 {0}": " · failed {0}",
 " · 앞 120개 위치 표시": " · first 120 places shown",
 " · 예: {0}{1}": " · e.g. {0}{1}",
 " · 인용 목록 먼저 필요 {0}": " · reference lists needed first {0}",
 " · 중복 {0}": " · duplicates {0}",
 " · 중지됨": " · stopped",
 " · 최근 조회 실패, 마지막 확인값 유지": " · the last lookup failed; the previous value is kept",
 " · 키 없이는 하루 약 10건입니다": " · without a key that is about ten requests a day",
 " · 판단 불가 {0}": " · undecided {0}",
 " · 편집할 수 없어 건너뜀 {0}개": " · {0} skipped as not editable",
 " · 표본 {0}/{1}": " · sample {0}/{1}",
 " · 확인 필요": " · needs checking",
 " 기본값 복원": " restore defaults",
 " 기본값을 적용하는 중…": " restoring defaults…",
 " 더 보기 · ": " more · ",
 " 메뉴 표시": " show menu",
 " 선택": " select",
 " 외 {0}명": " and {0} others",
 " 적용": " apply",
 " 페이지 범위": " page range",
 " 필터 해제": " clear filter",
 "#RRGGBB 색상을 입력하세요.": "Enter a #RRGGBB colour.",
 "#RRGGBB 형식의 색상을 선택하세요.": "Choose a colour in #RRGGBB form.",
 "#ffd400, 핵심 주장\n#ff6666, 확인 필요": "#ffd400, key claim\n#ff6666, needs checking",
 "(제목 없음)": "(untitled)",
 "1저자": "first author",
 "4805초": "4805 s",
 "AI 논지·논쟁 분석": "AI reading of arguments and disputes",
 "AI 논지·논쟁 분석 결과 — 초록 기준 밑그림": "AI reading of arguments and disputes — a sketch from abstracts",
 "AI 생성 결과 — 적용 전 확인": "AI output — check it before applying",
 "AI 생성 결과입니다. 원문과 비교한 뒤 적용하세요.": "This is AI output. Compare it with the original before applying.",
 "AI 서버 응답이 너무 깁니다. 더 짧은 글을 고르거나 모델을 바꾸세요.": "The reply from the AI server is too long. Choose a shorter text, or a different model.",
 "AI 서버 주소 (Chat Completions)": "AI server address (Chat Completions)",
 "AI 서버가 아무 내용도 보내지 않았습니다. 모델 이름을 확인하고 다시 시도하세요.": "The AI server sent nothing back. Check the model name and try again.",
 "AI 서비스 응답 오류: HTTP ": "The AI service returned an error: HTTP ",
 "AI 요약": "AI summary",
 "AI 요약·비교": "AI summaries and comparisons",
 "AI 요청을 완료하지 못했습니다. 연결 설정을 확인하세요.": "The AI request could not be completed. Check the connection settings.",
 "AI 요청을 중지했습니다.": "The AI request was stopped.",
 "AI 읽기 메모 제안 사용": "Enable AI reading-note suggestions",
 "AI 태그 제안 사용": "Enable AI tag suggestions",
 "AI가 태그를 목록으로 주지 않았습니다. 다시 시도하거나 다른 모델을 쓰세요.": "The AI did not answer with a list of tags. Try again, or use a different model.",
 "API 키": "API key",
 "Annotations · 색상 막대는 주석이 있는 페이지를 표시; 문서 전체 진행률로 추정하지 않음": "Annotations · the colour bar marks the pages that carry annotations; it is not an estimate of progress through the document",
 "CSS 규칙의 중괄호를 확인하세요.": "Check the braces in the CSS rule.",
 "CSV 복사": "Copy as CSV",
 "Clarivate JCR의 Groups와 Categories · 기관 접근 또는 계정 로그인이 필요할 수 있습니다": "Clarivate JCR groups and categories · may need institutional access or an account",
 "Custom 패널 CSS": "Custom panel CSS",
 "Custom 패널과 추가 열의 표시를 조절합니다. PDF 색상은 읽기 진행에서 설정하세요.": "Controls the custom panel and the extra columns. PDF colours are set under Reading progress.",
 "DOAJ 등재": "in DOAJ",
 "DOI 확인": "Check DOI",
 "DOI가 없어 자동으로 가져올 수 없습니다. 문헌 정보에 DOI를 넣은 뒤 다시 실행하세요.": "There is no DOI to fetch by. Add one to the item and run this again.",
 "DOI가 없어 철회 여부를 확인할 수 없습니다.": "There is no DOI, so retraction cannot be checked.",
 "Europe PMC에서 찾지 못했습니다": "Not found in Europe PMC",
 "Extra는 동기화되고 직접 고칠 수 있으며, 태그 목록에는 나타나지 않습니다.": "Extra syncs, can be edited by hand, and does not appear in the tag list.",
 "Figure·Table로 시작하는 주석 제외": "Skip annotations that begin with Figure or Table",
 "IF · 공식 카탈로그·저장 데이터 범위": "IF · official catalogue and stored data",
 "IF 높은 순": "Highest IF first",
 "IF 미확인": "IF unknown",
 "IF 열 사용": "Enable the IF column",
 "IF 확인 {0}개 · 조회 실패 {1}개 · 미등록 저널 {2}개. 기존 확인된 값은 유지됩니다.": "{0} IFs checked · {1} failed · {2} journals not listed. Values already confirmed are kept.",
 "JCR 목록 정렬": "Sort the JCR list",
 "JCR 순위": "JCR rank",
 "JCR 원본 열기": "Open JCR source",
 "JCR 원본에서 저널 확인": "See the journals at the JCR source",
 "JCR 저널 수": "JCR journals",
 "JCR 카테고리": "JCR category",
 "JCR 카테고리 탐색": "Browse JCR categories",
 "JCR 카테고리 표": "JCR category table",
 "JCR 카테고리로 돌아가기": "Back to JCR categories",
 "JCR 카테고리의 저널 표": "Journals of the JCR category",
 "JCR 표준 약어": "JCR standard abbreviation",
 "JCR에서 보기": "Open in JCR",
 "JIF 백분위": "JIF percentile",
 "JIF 순위": "JIF rank",
 "JIF 중앙값": "Median JIF",
 "JIF가 없으면 분야 안에서 줄을 세울 수 없습니다.": "Without a JIF there is nothing to order it by inside its subject.",
 "Journal Citation Reports의 저널 페이지 · 기관 로그인이 필요합니다": "The journal\\u2019s page on Journal Citation Reports · needs an institutional login",
 "Journal Tags / 저널 지표 · 추가 등급 조회는 본인의 easyScholar 키 필요": "Journal tags / metrics · the extra rank lookup needs your own easyScholar key",
 "OA 선택 시 APC ${0}": "APC ${0} when OA is chosen",
 "ORCID 열기": "Open ORCID",
 "ORCID에 등록된 개인 홈페이지에서 사진을 찾습니다. 저자를 열 때만 요청합니다.": "Looks for a photo on the personal homepage listed in ORCID. Requested only when you open an author.",
 "OpenAlex API 키 (선택)": "OpenAlex API key (optional)",
 "OpenAlex 기준 누적 논문 수와 2년 평균 피인용 (공식 JIF 아님)": "Papers to date and two-year mean citedness, per OpenAlex (not the official JIF)",
 "OpenAlex 기준 저널 h-index": "Journal h-index, per OpenAlex",
 "OpenAlex 분야": "OpenAlex subject",
 "OpenAlex 분야별 저장 JIF 비교입니다. 로컬 순위·Q는 자체 계산이며, 저장 Q는 카테고리 미확인 원본값입니다.": "A comparison of stored JIFs by OpenAlex subject. Local rank and Q are computed here; the stored Q is a source value whose category is unverified.",
 "OpenAlex 분야와 저장 JIF의 로컬 비교 · 공식 JCR 순위 아님": "A local comparison of stored JIFs by OpenAlex subject · not an official JCR rank",
 "OpenAlex 주제로 탐색": "Browse by OpenAlex subject",
 "OpenAlex 하루 한도를 다 썼습니다. {0}묶음이 남았고, 한국 시간 오전 9시에 초기화됩니다. 지금까지 확인한 결과는 저장했습니다.": "The OpenAlex daily allowance is used up. {0} batches are left and it resets at midnight UTC. What has been checked so far is saved.",
 "OpenAlex 하루 한도를 다 썼습니다. {0}종이 남았고, 한국 시간 오전 9시에 초기화됩니다.\n지금까지 받은 값은 저장했으니 내일 다시 실행하면 남은 것부터 이어서 채웁니다.": "The OpenAlex daily allowance is used up. {0} are left and it resets at midnight UTC.\nWhat has arrived is saved, so running it again tomorrow carries on from where it stopped.",
 "OpenAlex 하루 한도를 다 썼습니다. 한국 시간 오전 9시에 초기화되고, 다시 실행하면 남은 것부터 이어서 채웁니다.": "The OpenAlex daily allowance is used up. It resets at midnight UTC; run it again after that and it carries on from where it stopped.",
 "OpenAlex에서 관련 논문을 찾는 중…": "Looking for related papers on OpenAlex…",
 "OpenAlex에서 보기": "View on OpenAlex",
 "OpenAlex에서 이 논문의 저자를 찾지 못했습니다.": "OpenAlex has no authors for this paper.",
 "PDF Style 메뉴 → Switch PDF version · 같은 문헌에 속한 실제 존재하는 PDF만 선택; 기존 탭 유지": "PDF style menu → Switch PDF version · only PDFs that actually exist on the same item; the open tab is kept",
 "PDF 글자색": "PDF text",
 "PDF 배경색": "PDF background",
 "PDF 여백에 주석 표시": "Show annotations in the PDF margin",
 "PDF 주석 머리글 / 워크벤치 → 주석·역링크 · 같은 PDF의 다른 주석 및 다른 라이브러리 참조 구분": "PDF annotation header / Workbench → Annotations and backlinks · distinguishes other annotations in the same PDF from references in another library",
 "PDF 주석 우클릭·Style 메뉴 / 워크벤치 → 주석 · 동일 PDF·유형·색상인 하이라이트/밑줄, 같은 페이지 또는 인접 두 페이지; 위치·텍스트·메모·태그 보존, 나머지는 휴지통": "PDF annotation right-click and Style menu / Workbench → Annotations · highlights and underlines in one PDF of one type and colour, on the same page or two adjacent ones; position, text, comment and tags are kept, the rest go to the trash",
 "PDF 첨부 버전 전환 사용": "Enable switching between PDF versions",
 "PDF 테마": "PDF theme",
 "PDF 테마·사용자 색상·원래 모양 복원 사용": "Enable PDF themes, custom colours and restoring the original look",
 "PDF 테마와 여백 주석의 실제 표시·필터를 조절합니다.": "Controls how PDF themes and margin annotations are shown and filtered.",
 "PDF만": "PDF only",
 "PMC에 보관된 본문이 아니라 받을 수 없습니다": "The full text is not archived in PMC, so it cannot be fetched",
 "PMC에 없음 {0} · 보충자료 없음 {1}\n": "not in PMC {0} · no supplementary {1}\n",
 "Remark / 상세 문헌 메모": "Remark / detailed item note",
 "Style Custom 설정": "Style Custom settings",
 "Style Custom 설정 검색": "Search Style Custom settings",
 "Style Custom 연구 작업 패널": "Style Custom research panel",
 "Style Custom이 준비되지 않았습니다. 설정을 다시 여세요.": "Style Custom is not ready. Open the settings again.",
 "Tags / 제목 태그": "Tags / title tags",
 "USPTO Open Data Portal 키 (선택)": "USPTO Open Data Portal key (optional)",
 "ZotPoP 열기": "Open ZotPoP",
 "ZotPoP에서 이 논문 검색": "Search this paper in ZotPoP",
 "ZotPoP에서 이 저널 검색": "Search this journal in ZotPoP",
 "ZotPoP에서 찾기": "Find in ZotPoP",
 "ZotPoP이 설치되어 있지 않습니다. 도구 → 부가 기능에서 설치한 뒤 다시 시도하세요.": "ZotPoP is not installed. Install it from Tools → Add-ons and try again.",
 "Zotero 데이터 폴더/style-custom.json": "Zotero data folder/style-custom.json",
 "Zotero 문헌 창을 열어 주세요.": "Open a Zotero library window.",
 "Zotero 설정 → Style Custom → 번역·AI에 AI 서버 주소·모델·API 키를 넣으면 켜집니다. 요청은 버튼을 누를 때만 보냅니다.": "Turns on once the AI server address, model and API key are set under Zotero Settings → Style Custom → Translate · AI. A request is sent only when you press a button.",
 "Zotero의 첨부 미리보기를 쓸 수 없습니다. 「열기」로 파일을 여세요.": "Zotero's attachment preview is unavailable here. Use Open to open the file.",
 "api.openalex.org에만 Authorization 헤더로 보냅니다. openalex.org 계정에서 무료 발급되며, 비워 두면 키 없이 조회합니다.": "Sent as an Authorization header to api.openalex.org only. Free from an openalex.org account; left empty, lookups run without a key.",
 "easyScholar API 키": "easyScholar API key",
 "mailto 없음 — 익명 대기열을 씁니다. 설정 → 연락 이메일에 주소를 넣으면 빨라집니다.": "no mailto — requests use the anonymous queue. Settings → Contact e-mail makes them faster.",
 "{0}\n연결 {1}": "{0}\n{1} connections",
 "{0} {1}개 · {2} {3}종": "{0}: {1} · {2} {3}",
 "{0} {1}종 중 {2}위 · 상위 {3}% · Q{4}": "{0}: {2} of {1} · top {3}% · Q{4}",
 "{0} {1}종 중 {2}위 · 상위 {3}% · 로컬 Q{4}": "{0}: {2} of {1} · top {3}% · local Q{4}",
 "{0} · {1}개 · 눌러서 이 색만 보기": "{0} · {1} · click to show only this colour",
 "{0} · {1}개 · 다시 눌러 색 필터 해제": "{0} · {1} · press again to clear the colour filter",
 "{0} · {1}개 문헌": "{0} · {1} items",
 "{0} · {1}개 문헌 범위 · 내용 검색": "{0} · {1} items · searching their content",
 "{0} · {1}개 문헌{2}": "{0} · {1} items{2}",
 "{0} · {1}종": "{0} · {1} journals",
 "{0} · {1}편": "{0} · {1} papers",
 "{0} · 공식 IF를 아직 확인하지 못했습니다.": "{0} · the official IF has not been checked yet.",
 "{0} · 새 논문 {1}편": "{0} · {1} new",
 "{0} · 새 논문 없음 (확인 {1})": "{0} · nothing new (checked {1})",
 "{0} · 아직 확인하지 않음": "{0} · not checked yet",
 "{0} · 확인 {1}": "{0} · checked {1}",
 "{0} 단위": "in steps of {0}",
 "{0} 메모를 저장하지 못했습니다: {1}": "Could not save the note on {0}: {1}",
 "{0} 분류의 설정을 모두 기본값으로 되돌릴까요? API 키·비밀번호는 유지됩니다.": "Reset every setting under {0} to its default? API keys and passwords are kept.",
 "{0} 서버에 일시적인 문제가 있습니다({1}). 잠시 뒤 다시 시도하세요.": "{0} is having a temporary problem ({1}). Try again shortly.",
 "{0} 설정을 기본값으로 되돌렸습니다. API 키·비밀번호는 유지했습니다.": "{0} settings are back at their defaults. API keys and passwords were kept.",
 "{0} 요청이 실패했습니다{1}.": "The {0} request failed{1}.",
 "{0} 응답이 너무 늦어 중단했습니다. 네트워크를 확인하고 다시 시도하세요.": "{0} took too long to answer, so it was stopped. Check the network and try again.",
 "{0} 채우는 중 {1}/{2}": "Filling {0} {1}/{2}",
 "{0} 컬렉션으로 이동했습니다.": "Moved to the {0} collection.",
 "{0} 페이지별 읽은 시간": "{0}: time read per page",
 "{0} 표시": "Show {0}",
 "{0}: 2년 평균 피인용 ~{1} (OpenAlex 추정치, 공식 JIF 아님)": "{0}: two-year mean citedness ~{1} (an OpenAlex estimate, not an official JIF)",
 "{0}: OpenAlex에 이 저널의 지표가 없습니다.": "{0}: OpenAlex has no metric for this journal.",
 "{0}–{1} / {2}개": "{0}–{1} of {2}",
 "{0}–{1} 범위의 값을 입력하세요.": "Enter a value between {0} and {1}.",
 "{0}가 요청을 거절했습니다({1}). API 키가 필요하거나 만료됐는지 설정에서 확인하세요.": "{0} refused the request ({1}). Check in the settings whether an API key is needed or has expired.",
 "{0}개 문서 탭을 닫았습니다.": "Closed {0} document tabs.",
 "{0}개 문헌 선택": "{0} items selected",
 "{0}개 문헌 선택{1}": "{0} items selected{1}",
 "{0}개 문헌의 상호 연결을 해제했습니다.": "Unlinked {0} items from each other.",
 "{0}개 문헌의 색을 지웠습니다.": "Cleared the colour on {0} papers.",
 "{0}개 문헌의 주석 {1}개가 더 있습니다.": "{1} more annotations, across {0} papers.",
 "{0}개 설정 검색됨": "{0} settings found",
 "{0}개 적용": "{0} applied",
 "{0}개 주석의 색상을 변경했습니다.": "Recoloured {0} annotations.",
 "{0}개 항목의 별 태그를 정리했습니다. 평점은 그대로 유지됩니다.": "Tidied the star tags on {0} items. The ratings themselves are unchanged.",
 "{0}개 항목의 평점을 Extra의 \"Rating: N\"으로 옮기고 태그를 지웠습니다. 별점은 그대로입니다.": "Moved the ratings on {0} items into \"Rating: N\" in Extra and removed the tags. The ratings themselves are unchanged.",
 "{0}개는 아직 내용을 읽어보지 않았습니다 (우클릭 → 첨부파일 종류 판별)": "{0} have not been read yet (right-click → Judge attachment kinds)",
 "{0}개를 보충자료로 표시했습니다.": "Marked {0} as supplementary.",
 "{0}개의 표시를 해제했습니다.": "Unmarked {0}.",
 "{0}만 보기": "Only {0}",
 "{0}명이 새 논문 {1}편을 냈습니다. 요청 {2}회.": "{0} authors published {1} new papers. {2} requests.",
 "{0}번째 / {1}": "{0} of {1}",
 "{0}분": "{0}m",
 "{0}시간 {1}분": "{0}h {1}m",
 "{0}에 해당 기록이 없습니다. 논문 자체의 문제가 아니라 그 서비스가 모르는 것입니다.": "{0} has no record of it. That is not a problem with the paper; that service simply does not know it.",
 "{0}위 / {1}": "{0} of {1}",
 "{0}위 / {1}종 · 상위 {2}%": "{0} of {1} · top {2}%",
 "{0}위 / {1}종 · 상위 {2}% · 로컬 Q{3}": "{0} of {1} · top {2}% · local Q{3}",
 "{0}을(를) 관심 저자에서 뺐습니다.": "{0} is no longer followed.",
 "{0}의 최근 작업을 불러오는 중…": "Loading recent work by {0}…",
 "{0}의 하루 사용량을 다 썼습니다. {1} 뒤({2})에 초기화되고, ": "The daily allowance for {0} is used up. It resets in {1} (at {2}), ",
 "{0}점 이상": "{0} and above",
 "{0}종 조회 실패": "{0} journals failed",
 "{0}페이지 · {1}초": "page {0} · {1}s",
 "{0}페이지, {1}초": "page {0}, {1}s",
 "{0}편": "{0} papers",
 "{0}편 · 국제공동 {1} · 기관 등급 있음 {2}": "{0} papers · international {1} · with an institution tier {2}",
 "{0}편 · 이미 보유 {1}편": "{0} papers · {1} already held",
 "{0}편 · 읽음 {1} · 평균 피인용 {2}{3}": "{0} papers · read {1} · mean citations {2}{3}",
 "{0}편 · 초록 있음 {1}": "{0} papers · {1} with abstracts",
 "{0}편{1}": "{0} papers{1}",
 "{0}편에서 인용 {1}건": "{1} citations across {0} papers",
 "{0}편에서 참고문헌 {1}건 · 기관 {2}곳": "{1} references from {0} papers · {2} institutions",
 "{0}편은 너무 많습니다. 둘에서 여섯 편을 선택하세요.": "{0} papers is too many. Select two to six.",
 "«{0}»에 붙이기": "Attach to “{0}”",
 "↑↓ 이동 · Enter 열기 · Esc 닫기": "↑↓ move · Enter open · Esc close",
 "≈ {0} · OpenAlex 2년 평균 피인용 · {1}\n공식 JIF가 아니라 추정치입니다.": "≈ {0} · OpenAlex two-year mean citedness · {1}\nAn estimate, not an official JIF.",
 "가 없습니다.": " is missing.",
 "가리기": "Hide",
 "가져오는 중… ": "Importing… ",
 "가져오지 못했습니다. 잠시 뒤 다시 시도하세요.": "Could not fetch it. Try again in a moment.",
 "가져올 읽기 기록이 없습니다. (노트 {0}개 · 이미 보유 {1}개 · 대상 불명 {2}개)": "There is no reading history to import. ({0} notes · {1} already held · {2} with no known target)",
 "간격 넓게": "Comfortable",
 "간격 좁게": "Compact",
 "값을 읽지 못했습니다: {0}": "Could not read the value: {0}",
 "강조 색상": "Accent colour",
 "같은 이름의 보드가 이미 있습니다. 다른 이름을 쓰세요.": "A board with that name already exists. Use a different one.",
 "같은 파일이 두 번": "The same file twice",
 "개": "",
 "개 남음": " left",
 "개 설정을 읽지 못했습니다. 설정 다시 읽기로 재시도하세요.": " settings could not be read. Try Reload settings.",
 "개 열 설정": " columns",
 "개 적용": " applied",
 "개 탭": " tabs",
 "개수·즐겨찾기·정렬 기능을 선택합니다.": "Choose the count, favourite and sorting features.",
 "검색": "Search",
 "검색 결과 전체 선택": "Select all results",
 "검색 지우기": "Clear search",
 "검색된 기능": "Matching features",
 "검색에 맞는 그룹이 없습니다.": "No group matches the search.",
 "검색에 맞는 노트가 없습니다. 검색어를 바꿔 보세요.": "No note matches. Try a different search.",
 "검색에 맞는 설정이 없습니다. 검색어를 바꾸거나 지우세요.": "No setting matches. Change the search or clear it.",
 "검색에 맞는 저널이 없습니다.": "No journal matches the search.",
 "검색에 맞는 첨부가 없습니다. 검색어를 바꿔 보세요.": "No attachment matches. Try a different search.",
 "검색에 맞는 카테고리가 없습니다.": "No category matches the search.",
 "검색에 맞는 컬렉션이 없습니다.": "No collection matches the search.",
 "게재됨 →": "Published →",
 "결과 복사": "Copy result",
 "계정이 아닙니다. OpenAlex와 Crossref는 요청 URL에 ?mailto=주소를 붙이면 익명 요청보다 빠른 대기열(polite pool)에 넣어 줍니다. 대신 입력한 주소가 두 서비스의 서버 기록에 매 요청마다 남습니다. 비워 두면 아무것도 보내지 않고, 조회는 그대로 동작하되 느린 쪽 대기열을 씁니다. Zotero 로그인 계정을 대신 쓰는 일은 없습니다.": "This is not an account. OpenAlex and Crossref put a request carrying ?mailto=your-address into a faster queue than an anonymous one — their polite pool. In exchange, the address you enter appears in those two services' server logs on every request. Leave it blank and nothing is sent: lookups still work, they just use the slower queue. Your Zotero sign-in is never used instead.",
 "공개 접근 ({0})": "Open access ({0})",
 "공개 접근본이 없습니다.": "No open-access copy.",
 "공식 JCR 카테고리 보기": "Official JCR categories",
 "공식 JCR 카테고리 자료를 불러오지 못했습니다. 플러그인 업데이트를 확인하세요.": "The official JCR category data could not be loaded. Check for a plugin update.",
 "공식 JIF가 있는 저널은 그대로 두고, 없는 저널만 ~추정치로 채웁니다.": "Journals with an official JIF are left alone; only the rest are filled with a ~estimate.",
 "공식 값 새로고침": "Refresh the official value",
 "공저 {0}편": "{0} together",
 "공저자": "Co-authors",
 "공통 저자": "Shared authors",
 "공통 참고문헌": "Shared references",
 "공통 태그": "Shared tags",
 "관계 그래프": "Citation map",
 "관계 그래프 열기": "Open the citation map",
 "관계·태그·저자 그래프 사용": "Enable the citation, tag and author graphs",
 "관련 논문": "Related papers",
 "관련 논문은 문헌 하나를 기준으로 찾습니다. 문헌을 하나만 선택하세요.": "Related papers are found from one paper. Select a single item.",
 "관련 문헌": "Related",
 "관련 문헌 연결을 저장했습니다.": "The related-item link was saved.",
 "관련 문헌으로 연결": "Link as related",
 "관심 저자 {0}": "Followed authors {0}",
 "관심 저자 {0}명. 새 저자를 등록하려면 문헌을 하나 선택하세요.": "{0} followed authors. Select an item to watch a new one.",
 "관심 저자 {0}명의 새 논문을 확인하는 중…": "Checking {0} followed authors for new papers…",
 "관심 저자 새 논문": "New work by followed authors",
 "관심 저자 정렬": "Sort followed authors",
 "관심 저자 찾기": "Find a followed author",
 "관심 저자 특허": "Patents of followed authors",
 "관심 저자: {0}명 확인, 새 논문 없음": "Followed authors: {0} checked, nothing new",
 "관심 저자: {0}명이 새 논문 {1}편": "Followed authors: {1} new papers by {0}",
 "관심 저자는 {0}명까지 저장합니다. 목록에서 몇 명을 해제하세요.": "At most {0} followed authors are kept. Unwatch a few from the list.",
 "관심 저자로 등록": "Watch this author",
 "관심 저자에서 빼기": "Stop following",
 "관심 저자의 특허 출원·등록을 찾는 데만 씁니다. data.uspto.gov에서 MyUSPTO 계정으로 무료 발급됩니다. 키는 api.uspto.gov에만 보내며, 비워 두면 특허 확인은 건너뜁니다.": "Used only to find patents filed or granted to followed authors. Free from data.uspto.gov with a MyUSPTO account. The key is sent to api.uspto.gov only; left empty, the patent check is skipped.",
 "관심 해제": "Unwatch",
 "교신·책임저자": "Corresponding author",
 "교신저자": "corresponding author",
 "교신저자 표시가 없어 마지막 저자를 교신저자로 간주했습니다.": "No corresponding author is marked, so the last author was taken as one.",
 "교신저자가 {0}명입니다.": "There are {0} corresponding authors.",
 "구독형": "Subscription",
 "국가": "Country",
 "국제 공동연구": "International collaboration",
 "그때 다시 실행하면 남은 것부터 이어서 채웁니다. 지금까지 받은 값은 이미 저장했습니다.": "Run it again then and it will carry on from where it stopped. What has arrived is already saved.",
 "그래프 종류": "Kind of graph",
 "그래프 최대 문헌 수": "Maximum items in the graph",
 "그래프는 최대 {0}개 문헌을 표시합니다.": "The graph shows at most {0} items.",
 "그래프는 최대 {0}개 문헌을 표시합니다. 검색으로 범위를 좁히세요.": "The graph shows at most {0} items. Narrow the scope with a search.",
 "그룹": "Group",
 "그룹 또는 카테고리 목록이 일부만 수집되어 있습니다.": "Only part of the group or category list has been captured.",
 "그룹 보기": "View groups",
 "그룹 삭제": "Delete group",
 "그룹·카테고리 검색": "Search groups and categories",
 "그룹·카테고리 이름 검색": "Search group or category names",
 "그리지 않음: {0}": "Not drawn: {0}",
 "그림": "Image",
 "기관 전체 h-index 1400 이상 (상위 약 25%)": "Institution h-index of 1400 or more (about the top 25%)",
 "기관 전체 h-index 2000 이상 (이 라이브러리 논문 상위 약 10%)": "Institution h-index of 2000 or more (about the top 10% of papers here)",
 "기관 전체 h-index 400 미만": "Institution h-index below 400",
 "기관 전체 h-index 400 이상": "Institution h-index of 400 or more",
 "기능 바로 찾기": "Jump to a feature",
 "기능 찾기": "Find a feature",
 "기능 찾기 · ⌘/Ctrl K": "Find a feature · ⌘/Ctrl K",
 "기능별 작업 패널과 표시 밀도·목록 크기를 조절합니다.": "Controls the panels for each feature, the density and the list size.",
 "기록 간격·무활동 제외·상태 연동을 조절합니다. 읽기 기록은 로컬 파일에 저장합니다.": "Controls the recording interval, the idle cut-off and the link to reading status. The history is kept in a local file.",
 "기록·표시 갱신 간격 (ms)": "Record and refresh interval (ms)",
 "기록이 없어도 0초 표시": "Show 0s even with no record",
 "기본 1초. 비활성 창과 무활동 시간은 제외합니다.": "One second by default. Inactive windows and idle time are excluded.",
 "기본 Custom 열 표시": "Show the default custom columns",
 "기본 {0} · 허용 {1}–{2}": "Default {0} · allowed {1}–{2}",
 "기본 순서": "Default order",
 "기본값으로 되돌렸습니다.": "Back at the defaults.",
 "기본값으로 되돌리지 못했습니다: ": "Could not restore the default: ",
 "기존 태그 경로": "Existing tag path",
 "긴 제목 호버 스크롤": "Scroll long titles on hover",
 "꺼짐": "off",
 "나중에": "Later",
 "날짜 표시": "Date display",
 "내 논문 {0}편이 인용합니다": "{0} of my papers cite it",
 "내 라이브러리가 자주 인용하지만 갖고 있지 않은 논문 {0}": "Papers my library cites often but does not hold {0}",
 "내 라이브러리에 없음": "not in my library",
 "내 문헌": "My papers",
 "내 문헌 {0}편": "{0} of my papers",
 "내 문헌 많은 순": "Most of my papers first",
 "내 서재": "In my library",
 "내 서재 {0}": "My library {0}",
 "내 서재에 없는 저널": "Not in my library",
 "내림차순": "Descending",
 "내용 복사": "Copy",
 "네덜란드": "Netherlands",
 "네트워크에 연결할 수 없습니다.": "The network cannot be reached.",
 "노르웨이": "Norway",
 "노트": "Notes",
 "노트 검색·생성·편집 사용": "Enable note search, creation and editing",
 "노트 편집": "Edit note",
 "노트를 저장했습니다. 필요하면 저장한 노트를 열어 편집하세요.": "The note was saved. Open it to edit it if you need to.",
 "노트를 휴지통으로 옮겼습니다. Zotero 휴지통에서 복원할 수 있습니다.": "The note was moved to the trash. It can be restored from Zotero's trash.",
 "논문": "Papers",
 "논문 비교": "Compare",
 "논문 추가·수정 시 인용 수 조회 후 Extra 저장": "Look up citations when an item is added or edited and store them in Extra",
 "뉴질랜드": "New Zealand",
 "다른 논문": "Different paper",
 "다른 논문 {0}개": "{0} different paper",
 "다른 논문이 붙어 있음": "A different paper is attached",
 "다른논문×{0}": "other×{0}",
 "다시 찾기": "Search again",
 "다음": "Next",
 "다음 페이지": "Next page",
 "닫기": "Close",
 "대기": "Waiting",
 "대만": "Taiwan",
 "대분류": "Domain",
 "더 보기": "Show more",
 "데이터셋": "Dataset",
 "덴마크": "Denmark",
 "도구": "Tools",
 "독립 세로 탭 목록 사용": "Enable the standalone vertical tab list",
 "독립 첨부파일 {0}개는 본 문헌이 없어 태그를 그대로 두었습니다.": "{0} standalone attachments have no parent item, so their tags were left alone.",
 "독일": "Germany",
 "되돌릴 보드가 없습니다. 보드를 지운 뒤에만 되돌릴 수 있습니다.": "There is no board to bring back. This only works right after one is deleted.",
 "두 카드를 선택하세요.": "Select two cards.",
 "뒤로": "Back",
 "드래그하거나 방향키로 이동": "Drag, or move with the arrow keys",
 "등급 조회": "Look up rank",
 "등록 {0}": "granted {0}",
 "등록 당시: {0}": "When followed: {0}",
 "등록 저널 {0} · 이 라이브러리 저널 {1}종: 브랜드색 {2} · 규칙 {3} · 출판사색 {4} · 유도색 {5}": "{0} journals in the registry · {1} journals in this library: brand colour {2} · rule {3} · publisher colour {4} · derived {5}",
 "라이브러리": "Library",
 "라이브러리 저널 지표 채우기": "Fill in journal metrics for the library",
 "라이브러리 전체 인용 수 조회": "Look up citations for the whole library",
 "라이브러리에 문헌이 없습니다. ZotPoP으로 논문을 찾아 추가하세요.": "The library has no papers yet. Find and add some with ZotPoP.",
 "러시아": "Russia",
 "로컬 JIF 순번": "Local JIF position",
 "로컬 분야 순위": "Local subject rank",
 "로컬 분야 순위 높은 순": "Highest local subject rank",
 "리더 모양 원래대로": "Reset the reader's appearance",
 "리더 사이드바 토글 사용": "Enable the reader sidebar toggle",
 "리더 사이드바 표시": "Show reader sidebar",
 "리더 사이드바와 세로 탭·저장 그룹을 조절합니다.": "Controls the reader sidebar, vertical tabs and saved groups.",
 "리더·주석": "Reader and annotations",
 "마지막 연도": "To year",
 "마지막 읽기·수정·추가 시각이 최근인 순서입니다.": "Ordered by the most recent read, edit or addition.",
 "마지막 확인": "Last checked",
 "마지막 확인 이후 새 논문 {0}": "New since the last check {0}",
 "마지막 확인 이후 새 논문 {0}편": "{0} new papers since the last check",
 "마지막 확인 이후 새 특허 {0}건": "{0} new patents since the last check",
 "마지막 확인 이후 새로 보인 특허": "A patent that appeared since the last check",
 "마지막 확인 이후 처음 같이 낸 저자": "Co-author not seen on any earlier paper",
 "마지막에 이름을 올린 저자를 이 논문의 책임저자로 보고, 그 사람의 최근 논문·소속 이동·특허를 엽니다.": "Takes the last-listed author as the paper's senior author and opens their recent papers, moves between institutions and patents.",
 "많이": "More",
 "먼저 「비교 분석」을 눌러 결과를 받으세요.": "Press Compare first to get a result to save.",
 "먼저 논문의 제목과 초록을 가져오세요.": "Fetch the paper's title and abstract first.",
 "먼저 문헌을 선택하세요.": "Select an item first.",
 "먼저 세어만 보기": "Count first, download nothing",
 "먼저 할 것": "Start here",
 "메뉴 기본값 복원": "Restore menu defaults",
 "메뉴·디자인": "Menus and design",
 "메모": "Note",
 "메모 저장": "Save note",
 "메모 주석 표시": "Show notes",
 "메모 카드 추가": "Add a note card",
 "메모를 저장했습니다.": "Note saved.",
 "메인 문헌 목록에서 해당 열을 표시합니다.": "Shows that column in the main item list.",
 "메인 문헌 목록의 지표·상태·별점·읽기 시간과 추가 열을 조절합니다.": "Controls the metric, status, rating, reading-time and extra columns in the main item list.",
 "명": " people",
 "몇 시간·며칠 전": "Hours or days ago",
 "모델 이름": "Model name",
 "모두 보기": "Show all",
 "모든 별점": "Any rating",
 "모든 유형": "All types",
 "모든 일반 태그": "All ordinary tags",
 "모든 읽기 상태": "Any status",
 "모든 종류": "Every kind",
 "모든 파일": "All files",
 "목록 관리": "Manage list",
 "목록 복사": "Copy list",
 "목록에서 값을 선택하세요.": "Choose a value from the list.",
 "목록으로": "As a list",
 "목록의 값을 선택하세요.": "Choose a value from the list.",
 "무활동 제외 기준 (초)": "Idle threshold (seconds)",
 "문서": "Document",
 "문서 탭 활동 시 수정일 갱신": "Update Modified when a document tab is used",
 "문헌": "Item",
 "문헌 {0} · 연결 {1}": "{0} items · {1} connections",
 "문헌 {0}개 · PDF {1}개를 첫 페이지로 판별했습니다.\n": "Judged {1} PDFs on {0} items by their first page.\n",
 "문헌 관계 그래프": "Item citation map",
 "문헌 노트 편집": "Edit the note",
 "문헌 많은 순": "Most items",
 "문헌 목록에서 대상 문헌을 선택하세요.": "Select the item in the item list.",
 "문헌 보기": "Show item",
 "문헌 상세 필터": "Detailed filters",
 "문헌 상세·노트·주석·필터·정렬·페이지 탐색 사용": "Enable item detail, notes, annotations, filters, sorting and paging",
 "문헌 상세에 노트 직접 표시 사용": "Show notes directly in the item detail",
 "문헌 상세에 주석 직접 표시 사용": "Show annotations directly in the item detail",
 "문헌 열기": "Open item",
 "문헌 유형 필터": "Item type",
 "문헌 정렬": "Sort",
 "문헌 종류": "Kinds of item",
 "문헌 페이지 범위": "Page range",
 "문헌을 가져오면 관계 그래프가 나타납니다.": "The graph appears once items are loaded.",
 "문헌을 둘 이상 선택하면 함께 읽습니다.": "Select two or more items to read them together.",
 "문헌을 먼저 선택하세요.": "Select an item first.",
 "문헌을 선택하면 함께 비교하거나 연결할 수 있습니다.": "Select items to compare or link them.",
 "문헌을 읽는 중…": "Loading items…",
 "문헌을 찾지 못했습니다. 목록에서 다시 선택한 뒤 실행하세요.": "That paper could not be found. Select it in the list again and run this once more.",
 "문헌을 하나 고르면 OpenAlex에서 그 논문의 저자를 찾고, 관심 저자로 등록하면 새 논문·소속 이동·특허를 알려줍니다.": "Pick one paper and its authors are looked up on OpenAlex; follow one to hear of new papers, moves and patents.",
 "문헌을 하나 고르면 OpenAlex에서 세 가지를 찾아 옵니다.": "Pick one paper and three lists come from OpenAlex.",
 "문헌을 하나 선택하세요.": "Select exactly one item.",
 "문헌의 다른 변경 사항이 저장된 뒤 다시 시도하세요.": "Try again once the item's other changes have been saved.",
 "미국": "US",
 "미리보기": "Preview",
 "미확인": "unknown",
 "밑줄": "Underline",
 "밑줄 표시": "Show underlines",
 "바깥 논문 {0}": "{0} outside the library",
 "받을 수 있는 논문 {0}편\n\n": "{0} papers can be fetched\n\n",
 "받을 수 있는 논문이 몇 편인지만 세고, 내려받지는 않습니다.": "Counts how many papers could be fetched, without fetching any.",
 "발표": "Presentation",
 "발행·피인용": "Output · citedness",
 "발행연도": "Year",
 "밝게": "Light",
 "밝은 PDF": "Light PDF",
 "방금": "just now",
 "버전 {0}": "Version {0}",
 "번역 · AI": "Translate · AI",
 "번역·AI": "Translation and AI",
 "번역·AI 분류의 AI 서버 주소·모델·API 키가 있어야 켜집니다. 요청은 버튼을 누를 때만 보냅니다.": "Needs the AI server address, model and API key under Translate · AI. A request is sent only when you press the button.",
 "번역·AI 설정에 AI 서버 주소와 모델을 넣으면 켜집니다.": "Turns on once an AI server address and a model are set under Translate · AI.",
 "번역·요약할 문헌 하나를 선택하세요. AI 서버 주소와 모델은 설정에서 연결합니다.": "Select one paper to translate or summarise. The AI server address and model are set in the settings.",
 "범위에 맞는 숫자를 입력하세요{0}.": "Enter a number within range{0}.",
 "벨기에": "Belgium",
 "별도 저널 등급 조회용입니다. IF는 공식 카탈로그·검증된 저장값과 자동 매칭합니다.": "For the separate journal-rank lookup. The IF is matched against the official catalogue and verified stored values.",
 "별점": "Rating",
 "별점 {0}/5": "Rating {0}/5",
 "별점 높은 순": "Highest rated",
 "별점 없음": "No rating",
 "별점 열 표시": "Show the Rating column",
 "별점 지우기": "Clear rating",
 "병합은 같은 PDF·유형·색상에, 같은 페이지 또는 인접한 두 페이지에서만 됩니다. 기존 참조 노트의 링크는 바뀌지 않습니다.": "Merging works only within one PDF, one type and one colour, on the same page or two adjacent ones. Links in existing notes are not changed.",
 "보고서": "Report",
 "보드 만들기": "New board",
 "보드 삭제": "Delete board",
 "보드 선택": "Choose board",
 "보드 이름": "Board name",
 "보드 이름 변경": "Rename board",
 "보드 이름을 입력하세요.": "Enter a board name.",
 "보드 하나에 항목은 500개까지입니다. 몇 개를 빼고 다시 넣으세요.": "Five hundred items is the limit for one board. Take some out and add again.",
 "보드는 100개까지 만들 수 있습니다. 쓰지 않는 보드를 지우세요.": "A hundred boards is the limit. Delete one you no longer use.",
 "보드를 만들고 선택한 문헌을 카드로 추가하세요.": "Make a board and add the selected items as cards.",
 "보유 문헌": "Library",
 "보유 문헌 → 자세히 / 노트 탭 · 단일 문헌 상세에서 노트·주석 함께 표시": "Library → Details / Notes · shows notes and annotations together in a single item's detail",
 "보유 문헌 → 자세히 / 주석 탭 · 다른 탭·문헌으로 전환 시 늦은 응답 무시": "Library → Details / Annotations · a late answer is ignored once you move to another tab or item",
 "보유 문헌에서 고르기": "Pick from my papers",
 "보유 중": "In library",
 "보유하지 않은 논문은 행의 버튼으로 ZotPoP에서 바로 찾거나 가져올 수 있습니다.": "A paper you do not hold can be searched or imported through ZotPoP from its row.",
 "보이는 문헌 인용 수 자동 조회": "Look up citations for visible items automatically",
 "보이는 주석 전체 선택": "Select every annotation shown",
 "보충자료": "Supplementary",
 "보충자료 {0} · 중복 {1}": "supplementary {0} · duplicate {1}",
 "보충자료 {0} · 중복 {1} · 다른 논문 {2}": "supplementary {0} · duplicate {1} · different paper {2}",
 "보충자료 {0}개": "{0} supplementary",
 "보충자료 {0}개 추가 · 이미 있음 {1} · 없음 {2} · 미확인 {3} · 실패 {4}": "{0} supplementary files added · {1} already held · {2} none · {3} unchecked · {4} failed",
 "보충자료 — 클릭하면 열립니다": "Supplementary — click to open",
 "보충자료 내려받기": "Download supplementary",
 "보충자료 표시 해제": "Unmark as supplementary",
 "보충자료가 {0}MB로 너무 커서 건너뜀습니다": "The supplementary file is {0}MB, too large, so it was skipped",
 "보충자료가 없는 논문입니다": "This paper has no supplementary material",
 "보충자료는 일반 문헌에만 붙일 수 있습니다. 첨부파일이나 노트 말고 문헌을 고르세요.": "Supplementary files attach to a paper, not to an attachment or a note. Select the paper itself.",
 "보충자료를 옮겼습니다. Zotero에서 되돌릴 수 있습니다.": "The supplementary file was moved. Zotero can undo this.",
 "보충자료를 원논문으로 옮겼습니다{0}. Zotero에서 되돌릴 수 있습니다.": "The supplementary file was moved to the original paper{0}. Zotero can undo this.",
 "보충자료만 있는 문헌": "Items holding only supplementary material",
 "복원": "Restore",
 "복원 {0} · 찾지 못함 {1}": "restored {0} · not found {1}",
 "본문 {0} · 보충자료 {1} · 중복 {2} · 다른 논문 {3}": "article {0} · supplementary {1} · duplicate {2} · different paper {3}",
 "본문 {0}개": "{0} article",
 "본문 발췌 표시 글자 수": "Excerpt length",
 "본문·보충자료·중복·다른 논문으로 나눕니다.": "Tells the full text, supplementary files, duplicates and other papers apart.",
 "분 전": "m ago",
 "분석이 왔습니다. 초록만 읽고 쓴 밑그림이니 본문과 대조해 판단하세요.": "The reading is in. It was written from abstracts alone; judge it against the full texts.",
 "분야": "Field",
 "분야 고르기": "Choose a field",
 "분야 미상": "Subject unknown",
 "분야 미확인": "Field unknown",
 "분야 선택 지우기": "Clear the field choice",
 "분야 순위": "In subject",
 "분야 순위 높은 순": "Highest in its subject",
 "분야가 있는 저널": "journals with a subject",
 "분야별로 묶기": "Group by field",
 "불러오지 못했습니다. 새로고침으로 다시 시도하세요.": "Could not load. Try again with Refresh.",
 "뷰 그룹": "View groups",
 "뷰 그룹 이름": "View group name",
 "뷰 그룹 이름 변경": "Rename view group",
 "뷰·작업 패널": "Views and panels",
 "브라질": "Brazil",
 "비교 다음 페이지": "Next comparison page",
 "비교 이전 페이지": "Previous comparison page",
 "비교 항목 선택": "Choose what to compare",
 "비교 항목: ": "Compared: ",
 "비교표 한 페이지 문헌 수": "Items per comparison page",
 "비교하려면 문헌을 둘 이상 선택하세요.": "Select at least two items to compare.",
 "비교하려면 최소 한 편은 남아 있어야 합니다.": "Leave at least one paper in the comparison.",
 "비밀번호로 가려 표시합니다. 분류 기본값 복원으로 지워지지 않습니다.": "Shown masked, like a password. Restoring a category's defaults does not clear it.",
 "비어 있음": "Empty",
 "비워 두면 기본 개요(핵심 주장 · 논리 흐름 · 근거의 강점·한계 · 공통 기반 · 논쟁 여지와 판가름할 증거 · 열린 질문)를 씁니다. 출력 언어와 '지어내지 말 것'은 항상 덧붙습니다.": "Left empty, the default outline is used (core claim · line of argument · strength and limits of the evidence · common ground · points of contention with the deciding evidence · open questions). The output language and 'do not invent' are always appended.",
 "비워 두어도 동작하지만, 채우면 인용 수·저널 정보·AI 기능이 열립니다.": "Everything works with these blank; filling them unlocks citation counts, journal facts and the AI features.",
 "빈 응답": "Empty response",
 "빈 칸 채우기": "Fill the gaps",
 "빈 컬렉션 숨기기": "Hide empty collections",
 "빠른 조회 대기열": "Faster lookup queue",
 "사분위": "Quartile",
 "사용자 PDF 글자": "Custom PDF text",
 "사용자 PDF 배경": "Custom PDF background",
 "사용자 PDF 테마 적용": "Apply custom PDF theme",
 "사용자 색상": "Custom colours",
 "사용할 모델과 요청 문구를 직접 설정합니다. 요청은 사용자가 실행할 때만 전송됩니다.": "You choose the model and the wording of the request. Nothing is sent unless you ask for it.",
 "사이드바·탭": "Sidebar and tabs",
 "사전 {0}개 · 열·탭 {1}개 중 미번역 {2}": "{0} entries · {2} of {1} column and tab names untranslated",
 "사진 출처: {0}": "Photo: {0}",
 "삭제": "Delete",
 "삭제 취소": "Undo delete",
 "삭제하지 않고 Zotero 휴지통으로 옮깁니다": "Moves it to Zotero's trash rather than deleting it",
 "삭제할 보드를 선택하세요.": "Choose a board to delete.",
 "상세 보기": "Details",
 "상세 필터": "Filters",
 "상위": "High",
 "상태": "Status",
 "새": "New",
 "새 노트 내용": "New note",
 "새 노트 저장": "Save the note",
 "새 논문": "New papers",
 "새 논문 {0}편 확인함": "Marked {0} new papers as seen",
 "새 논문 다시 확인": "Check again for new papers",
 "새 논문 없음": "Nothing new",
 "새 논문 한 번에 확인": "Check all at once",
 "새 논문 확인 중 {0}/{1}": "Checking for new papers {0}/{1}",
 "새 논문은 없습니다. 저자 {0}명을 요청 {1}회로 확인했습니다.": "Nothing new. {0} authors were checked in {1} requests.",
 "새 메모": "New note",
 "새 보드 이름": "New board name",
 "새 소식 순": "Most news first",
 "새 소식만": "Only with news",
 "새 주석 팔레트 이름": "New palette name",
 "새 태그 경로": "New tag path",
 "새로고침": "Refresh",
 "색 없음": "no colour",
 "색 지우기": "Clear colour",
 "색 표시": "Show colour",
 "색 필터 해제": "Clear the colour filter",
 "색상 이름": "Colour name",
 "색상 이름 저장": "Save colour name",
 "색상 태그 표시 사용": "Enable coloured tags",
 "색상과 이름을 쉼표로 구분하세요.": "Separate the colour and the name with a comma.",
 "색상의 의미": "What the colours mean",
 "색상이 지정된 태그": "Tags with a colour",
 "색인": "Index",
 "서로 다른 두 카드를 선택하세요.": "Select two different cards.",
 "선택": "Select",
 "선택 {0}개": "{0} selected",
 "선택 문헌 연결·상호 연결 해제 사용": "Enable linking and unlinking the selection",
 "선택 문헌 인용 수 조회": "Look up citations for the selection",
 "선택 문헌 추가": "Add the selection",
 "선택 문헌 태그 이름 변경": "Rename tag on selection",
 "선택 문헌끼리 연결 해제": "Unlink selected",
 "선택 문헌에 적용": "Apply to the selection",
 "선택 문헌에 태그 추가": "Add tags to selection",
 "선택 문헌에서 태그 제거": "Remove tags from selection",
 "선택 저널 공식 IF 확인": "Check the official IF for the selected journal",
 "선택 저널 등급 조회": "Look up the rank for the selected journal",
 "선택 주석 병합": "Merge selected",
 "선택 주석 병합 사용": "Enable merging annotations",
 "선택 주석 새 색상": "New colour for the selection",
 "선택 주석 색 바꾸기": "Recolour selected",
 "선택 주석 색상 변경": "Recolour selected annotations",
 "선택 주석에 칠할 색": "The colour to paint the selected annotations",
 "선택 주석을 노트로": "Selected annotations to a note",
 "선택 카드 삭제": "Delete selected cards",
 "선택 해제": "Clear selection",
 "선택 해제 ({0})": "Clear selection ({0})",
 "선택: {0}": "Selected: {0}",
 "선택한 OpenAlex 경로의 로컬 JIF 비교 순위가 없습니다.": "No local JIF comparison rank for the chosen OpenAlex path.",
 "선택한 문헌": "Selected items",
 "선택한 문헌 ": "Selected ",
 "선택한 문헌 {0}개": "{0} selected items",
 "선택한 문헌 없음": "No item selected",
 "선택한 문헌 인용 수 새로고침": "Refresh citations for the selection",
 "선택한 문헌에 새 노트 작성": "Add a note to the selection",
 "선택한 문헌을 편집할 수 없습니다.": "The selected item cannot be edited.",
 "선택한 문헌의 저널 IF를 공식 페이지에서 다시 읽습니다.": "Reads the impact factor for the selected paper’s journal from the official page again.",
 "선택한 문헌의 제목·초록·메모를 설정된 AI 서비스에 요청 중…": "Sending the selected titles, abstracts and notes to the configured AI service…",
 "선택한 문헌의 첨부파일": "Attachments on the selected item",
 "선택한 문헌이 철회됐는지, 공개접근본이 있는지 확인합니다.": "Checks whether the selected papers are retracted and whether an open copy exists.",
 "선택한 텍스트가 너무 깁니다. 50,000자 이하로 줄이세요.": "The selected text is too long. Cut it to 50,000 characters or fewer.",
 "선택한 텍스트를 설정된 AI 서비스에 요청 중…": "Sending the selected text to the configured AI service…",
 "선택한 파일을 보충자료로 표시": "Mark the selected files as supplementary",
 "설정 {0} → {1} · 사전 {2}개 · 예: {3}": "setting {0} → {1} · {2} entries · e.g. {3}",
 "설정 다시 읽기": "Reload settings",
 "설정 분류": "Category",
 "설정 이름·설명 검색": "Search settings",
 "설정된 간격에 맞는 숫자를 입력하세요.": "Enter a number that fits the step.",
 "설정에서 AI 모델을 지정하세요.": "Name an AI model in the settings.",
 "설정에서 AI 서버 주소와 모델을 먼저 입력하세요.": "Enter the AI server address and the model in the settings first.",
 "설정에서 https로 시작하는 AI 서버 주소나 localhost 주소를 입력하세요.": "Enter an AI server address beginning with https, or a localhost address, in the settings.",
 "설정에서 본인의 easyScholar API 키를 입력하세요.": "Enter your own easyScholar API key in the settings.",
 "설정에서 이 기능을 켜세요.": "Turn this on in the settings.",
 "설정을 불러오는 중…": "Loading settings…",
 "설정을 불러왔습니다.": "Settings loaded.",
 "설정을 열지 못했습니다: ": "Could not open settings: ",
 "성공한 인용 수 재조회 간격 (일)": "Days before a successful citation lookup is repeated",
 "세로 탭 목록 표시": "Show vertical tab list",
 "세부 분야": "Subfield",
 "세피아": "Sepia",
 "세피아 PDF": "Sepia PDF",
 "소속": "Affiliation",
 "소속 미상": "affiliation unknown",
 "소속 미확인": "Affiliation unknown",
 "소속 이동 · {0} → {1} · {2} 확인": "Moved · {0} → {1} · checked {2}",
 "소속 이동 · {0} → {1} · {2}년부터 · {3} 확인": "Moved · {0} → {1} · since {2} · checked {3}",
 "소속순": "By place",
 "소속이 바뀐 것으로 보입니다 · {0} 확인 · OpenAlex 저자 기록의 현재 소속 기준": "Appears to have moved · checked {0} · by the current affiliations on the OpenAlex author record",
 "소속이 바뀐 것으로 보입니다 · {0}년부터 · {1} 확인 · OpenAlex 저자 기록의 현재 소속 기준": "Appears to have moved · since {0} · checked {1} · by the current affiliations on the OpenAlex author record",
 "소프트웨어": "Software",
 "수집": "captured",
 "수집된 저널": "captured journals",
 "수집된 카테고리": "Captured categories",
 "숨겨진 탭입니다. 스타일 편집에서 켜세요.": "This tab is hidden. Turn it on under Appearance.",
 "숫자 정렬에서 범위값과 미확인 값은 마지막에 표시합니다.": "When sorting by a figure, ranges and unknown values go last.",
 "숫자를 입력하세요.": "Enter a number.",
 "쉼표로 DOI, publisher, language 등 Zotero 필드명을 입력합니다.": "Enter Zotero field names such as DOI, publisher or language, separated by commas.",
 "스웨덴": "Sweden",
 "스위스": "Switzerland",
 "스크롤 속도 (px/s)": "Scroll speed (px/s)",
 "스크롤 시작 대기 (ms)": "Delay before scrolling (ms)",
 "스타일 저장": "Save style",
 "스타일 편집": "Style editor",
 "스타일 편집 / 문헌 제목": "Style editor / item title",
 "스타일 편집 → 수정일 갱신 · 기본 꺼짐; 사용자 선택 시 첨부·부모 날짜 갱신": "Style editor → update Modified · off by default; when chosen, the attachment's and parent's dates are updated",
 "스타일 편집 → 안 읽은 제목 굵게": "Style editor → bold unread titles",
 "스페인": "Spain",
 "시간 전": "h ago",
 "시작 연도": "From year",
 "식별자가 없어 조회할 수 없습니다": "There is no identifier to look it up by",
 "신문 기사": "Newspaper article",
 "신호 확인 {0}개 · 미확인 {1}개 · DOI 없음 {2}개 · 조회 오류 {3}개": "{0} signals checked · {1} unchecked · {2} with no DOI · {3} lookup errors",
 "실선 화살표는 실제 인용 · 점선은 공통 참고문헌 · 네모는 내가 갖고 있지 않은 논문 · 크기는 이 라이브러리 안에서의 중심성 · 색은 출판사": "A solid arrow is a real citation · a dotted line means shared references · a square is a paper you do not hold · size is centrality within this library · colour is the publisher",
 "실제 제공자와 조회 주기·메타데이터 저장을 설정합니다.": "Sets the provider, how often it is asked and where the metadata is stored.",
 "실행하는 중…": "Running…",
 "실행하지 못했습니다: ": "Could not run: ",
 "실행했습니다.": "Done.",
 "싱가포르": "Singapore",
 "아일랜드": "Ireland",
 "아직 관심 저자가 없습니다. 문헌을 하나 선택하면 그 저자를 등록할 수 있습니다.": "No authors are followed yet. Select an item to watch one of its authors.",
 "아직 비어 있는 것": "Still blank",
 "아직 심사 전 원고입니다. 정식 게재본은 나중에 따로 나올 수 있습니다.": "An unrefereed manuscript. A formally published version may follow separately.",
 "아직 안 읽은 {0}개 판별": "Judge the {0} not yet read",
 "아직 없음": "Not yet",
 "아직 인용 목록이 없습니다. “인용 목록 가져오기”를 누르면 실제 인용 관계로 바뀝니다. 그때까지는 관련 문헌 연결을 보여줍니다.": "No reference lists yet. Press “Fetch reference lists” to switch to real citations; until then this shows related-item links.",
 "아직 적용하지 않았습니다.": "Not applied yet.",
 "아직 조회 전 (인용 목록 가져오기를 실행하세요)": "Not looked up yet (run “Fetch reference lists”)",
 "아직 조회하지 않았습니다. 연구 작업 패널 → 정리 › 관계 그래프 → 인용 목록 가져오기": "Not looked up yet. Research panel → Organise › Citation map → Fetch reference lists",
 "아직 조회하지 않은 인용 수입니다. 0회 인용과 구분합니다.": "This citation count has not been looked up, which is not the same as zero.",
 "안 읽은 제목 굵게": "Bold unread titles",
 "안 읽음": "unread",
 "알겠어요": "Got it",
 "앱 밝게/어둡게 전환": "Toggle light/dark",
 "앱 밝게·어둡게 전환 사용": "Enable light/dark toggle",
 "약어": "Abbreviation",
 "어느 파일의 몇 쪽인지 기록이 없습니다. 그 PDF를 한 번 열어 읽은 뒤 다시 보세요.": "There is no record of which file and page this was. Open and read that PDF once, then look again.",
 "어두운 PDF": "Dark PDF",
 "어둡게": "Dark",
 "언어": "Language",
 "언어 / Language": "Language / 언어",
 "없음": "None",
 "여백 위치": "Margin side",
 "여백 주석 글자 크기": "Margin font size",
 "여백 주석 너비": "Margin width",
 "여백 주석 너비 (px)": "Margin width (px)",
 "여백 주석 설정 적용": "Apply margin settings",
 "여백 주석 설정을 적용했습니다.": "The margin settings were applied.",
 "여백 주석 위치": "Margin side",
 "여백 주석 최대 글자 수": "Margin text limit",
 "여백 주석 표시": "Show margin annotations",
 "여백 주석 표시 글자 수": "Margin text limit",
 "여백 주석과 위치·너비·표시 길이 설정 사용": "Enable margin annotations and their side, width and length",
 "역링크": "Backlinks",
 "역링크 기능이 꺼져 있습니다. 설정 → Style Custom → 보기에서 켜세요.": "Backlinks are turned off. Turn them on under Settings → Style Custom → Views.",
 "역링크를 확인할 문헌 하나를 선택하세요.": "Select one item to see its backlinks.",
 "연결 {0}": "{0} connections",
 "연결 없음 {0}": "{0} unconnected",
 "연결을 해제할 두 카드를 선택하세요.": "Select the two cards to unlink.",
 "연결이 너무 많아 강한 것부터 그렸습니다. 검색으로 범위를 좁히면 전부 보입니다.": "There were too many connections, so the strongest were drawn. Narrow the scope to see them all.",
 "연구 작업 패널": "Research panel",
 "연구 작업 패널 → 첨부 미리보기 · Zotero 9의 첨부 미리보기 기능": "Research panel → Attachment preview · Zotero 9's own attachment preview",
 "연구 작업 패널 열기": "Open the research panel",
 "연도 미상": "Year unknown",
 "연도 미표기": "year not stated",
 "연락 이메일 (선택)": "Contact e-mail (optional)",
 "열 배치 저장·복원·이름·내용 갱신 사용": "Enable saving, restoring, naming and updating column layouts",
 "열 표시": "Columns",
 "열 표시·순서·너비·정렬을 조절한 뒤 현재 뷰를 저장하세요.": "Adjust which columns show, their order, width and sorting, then save the view.",
 "열기": "Open",
 "열린 탭 저장": "Save open tabs",
 "열을 등록하지 못했습니다: ": "Could not register the column: ",
 "영국": "United Kingdom",
 "예: 주석, 비교, 탭…": "e.g. annotations, compare, tabs…",
 "오래 안 본 순": "Longest unchecked first",
 "오른쪽": "Right",
 "오름차순": "Ascending",
 "오스트리아": "Austria",
 "오픈액세스": "Open access",
 "오픈액세스가 아니라 받을 수 없음 {0}": "not open access, so unavailable {0}",
 "올바른 Zotero 필드 이름을 최대 12개 입력하세요.": "Enter up to 12 valid Zotero field names.",
 "옮기지 못했습니다.": "Could not move it.",
 "옮길 것이 없었습니다.": "There was nothing to move.",
 "완료": "done",
 "왼쪽": "Left",
 "요청 중지": "Stop",
 "요청을 완료하지 못했습니다. 다시 시도하세요.": "The request did not complete. Try again.",
 "요청이 중지되었습니다.": "The request was stopped.",
 "우려 표명": "Expression of concern",
 "우려 표명(expression of concern)이 게시된 논문입니다.": "An expression of concern has been published about this paper.",
 "워크벤치": "Workbench",
 "워크벤치 → 관계 그래프 · 화면 최대180노드, 검색으로 범위를 좁힘": "Workbench → Citation map · at most 180 nodes on screen; narrow the scope with a search",
 "워크벤치 → 노트 · 기존 리치 노트 편집은 Zotero 네이티브 편집기로 연결": "Workbench → Notes · editing an existing rich note opens Zotero's own editor",
 "워크벤치 → 보유 문헌 · 상태·별점·연도 필터 및 현재 컬렉션 범위; 화면100개씩 페이지 이동": "Workbench → Library · filters by status, rating and year within the current collection; 100 per page",
 "워크벤치 → 뷰 그룹 · 열 순서·너비·표시·정렬 저장": "Workbench → View groups · saves column order, width, visibility and sorting",
 "워크벤치 → 스타일 편집": "Workbench → Style editor",
 "워크벤치 → 스타일 편집 · 패널 범위 CSS, 외부 로딩 규칙 제외": "Workbench → Style editor · CSS scoped to the panel; rules that load external files are refused",
 "워크벤치 → 주석 · 현재 컬렉션·하위 컬렉션·선택 문헌 범위": "Workbench → Annotations · scoped to the collection, its subcollections or the selection",
 "워크벤치 → 중첩 태그": "Workbench → Nested tags",
 "워크벤치 → 중첩 태그 · 선택 문헌 범위에서만 변경; 상태·별점 전용 태그 경로 변경 제외": "Workbench → Nested tags · changes only within the selection; the status and rating tag paths are left alone",
 "워크벤치 → 최근 문헌": "Workbench → Recent",
 "워크벤치 → 캔버스 · 문헌/메모 카드; 보드 최대100개, 카드 최대500개": "Workbench → Canvas · item and note cards; at most 100 boards and 500 cards",
 "워크벤치 → 컬렉션": "Workbench → Collections",
 "워크벤치 → 탭 관리 · 그룹 이름·내용 갱신; 라이브러리 탭 보호": "Workbench → Tabs · rename groups and refresh their contents; the library tab is protected",
 "원고": "Manuscript",
 "원논문 보기": "Show the original paper",
 "원논문에 붙이기": "Attach to the original paper",
 "원논문으로 보이는 문헌: {0}": "This looks like the original paper: {0}",
 "원논문을 라이브러리에서 찾지 못했습니다.": "The original paper was not found in the library.",
 "원래 크기로": "Back to its size",
 "원래 테마 유지": "Keep the original",
 "원문": "Source",
 "원본 갱신": "source updated",
 "원본에서 수집하지 않은 값": "Not captured from the source",
 "웹페이지": "Web page",
 "위에 입력한 AI 서버 주소에만 인증 헤더로 보냅니다. 다른 곳으로는 보내지 않습니다.": "Sent as an authorisation header to the AI server address above, and nowhere else.",
 "유럽": "EP",
 "유형": "Type",
 "이 Zotero 버전은 첨부 미리보기를 지원하지 않습니다. 「열기」로 파일을 여세요.": "This version of Zotero has no attachment preview. Use Open to open the file.",
 "이 값은 해당 기능에 적용됩니다.": "This value applies to that feature.",
 "이 그룹의 카테고리 목록은 아직 수집되지 않았습니다.": "The categories of this group have not been captured yet.",
 "이 논문 이후에 나온 논문 중 이 논문을 참고문헌에 올린 것 — 후속 연구": "Later papers that list this one in their references — what followed",
 "이 논문 책임저자 추적": "Follow the senior author",
 "이 논문을 OpenAlex에서 찾지 못했습니다.": "This paper was not found on OpenAlex.",
 "이 논문을 인용한 논문": "Papers citing this one",
 "이 논문을 인용한 논문, 이 논문이 인용한 문헌, 주제가 가까운 논문을 OpenAlex에서 찾습니다.": "Finds papers that cite this one, the works it cites, and papers close to it in subject, from OpenAlex.",
 "이 논문의 관련 논문": "Related papers",
 "이 논문의 저자 {0}": "Authors of this paper {0}",
 "이 논문의 저자 {0}명 모두 보기": "Show all {0} authors of this paper",
 "이 논문이 인용한 문헌": "Works this paper cites",
 "이 논문이 참고문헌으로 든 문헌 — 바탕이 된 연구": "What this paper lists in its references — what it rests on",
 "이 라이브러리의 모든 문헌에 인용 수를 채우고 Extra에 기록합니다.": "Fills the citation count for every paper here and records it in Extra.",
 "이 문헌 메모": "Note on this item",
 "이 문헌에 같은 파일이 두 번 붙어 있습니다 — 클릭하면 열립니다": "The same file is attached twice here — click to open",
 "이 문헌에는 DOI나 제목이 없어 조회할 수 없습니다. 둘 중 하나를 채운 뒤 다시 실행하세요.": "This item has neither a DOI nor a title to look up. Fill in one of them and run this again.",
 "이 문헌은 다른 논문에 대한 정정·철회 공지입니다.": "This item is a correction or retraction notice about another paper.",
 "이 문헌을 가리키는 노트나 관련 문헌이 없습니다.": "No note or related item points at this one.",
 "이 문헌을 참조한 노트": "Notes that cite this item",
 "이 문헌의 메모": "Note on this item",
 "이 범위에 노트가 없습니다. 문헌을 선택해 새 노트를 작성하세요.": "There is no note in this scope. Select an item and write one.",
 "이 범위에서 연결이 없는 논문 {0}": "Papers with no connection in this scope {0}",
 "이 범위에서는 서로 인용하거나 참고문헌을 공유하는 논문이 없습니다. 범위를 넓혀보세요.": "In this scope no papers cite one another or share references. Try widening it.",
 "이 분류 기본값 복원": "Restore defaults for this category",
 "이 분야의 저널이 없습니다.": "No journals in this field.",
 "이 색의 주석이 없습니다. 색 필터가 켜져 있습니다.": "No annotations in this colour. A colour filter is on.",
 "이 서재에서 이 저널의 문헌": "This journal\\u2019s papers in this library",
 "이 수를 넘는 주석은 「더 보기」를 누를 때 이어서 그립니다. 주석이 수백 개인 서재에서 탭이 빨리 열립니다.": "Anything past this is drawn when you press Show more. It is what makes the tab open quickly in a library with hundreds of annotations.",
 "이 식별자를 읽을 수 있는 번역기가 없습니다. DOI·PMID·arXiv 번호 중 하나로 다시 시도하세요.": "No translator can read that identifier. Try a DOI, a PMID or an arXiv number instead.",
 "이 저널 문헌 보기": "Show its papers",
 "이 저널의 공식 IF를 아직 확인하지 못했습니다. 저널명과 ISSN을 확인하세요.": "This journal's official IF has not been checked. Check the journal name and ISSN.",
 "이 주석을 인용한 노트가 없습니다.": "No note cites this annotation.",
 "이 주석의 메모": "Note on this annotation",
 "이 창에서는 저널 지표를 조회할 수 없습니다. Zotero 기본 창에서 다시 실행하세요.": "Journal figures cannot be looked up from this window. Run it again from the main Zotero window.",
 "이 창에서는 탭을 열 수 없습니다.": "This window cannot open tabs.",
 "이 첨부는 미리보기를 지원하지 않습니다. 열기로 확인하세요.": "This attachment cannot be previewed. Use Open instead.",
 "이 카테고리를 수집 자료에서 찾을 수 없습니다.": "This category is not in the captured data.",
 "이 카테고리에 표시할 저널이 없습니다.": "There are no journals to show in this category.",
 "이 카테고리의 저널 목록은 아직 수집되지 않았습니다.": "The journals of this category have not been captured yet.",
 "이 태그만": "Only this tag",
 "이 탭 외 문서 탭 닫기": "Close other document tabs",
 "이 프리프린트는 이후 정식 게재되었습니다.": "This preprint was later formally published.",
 "이동": "Move",
 "이름": "Name",
 "이름 · 소속 · OpenAlex id, 탭으로 구분": "Name · place · OpenAlex id, tab-separated",
 "이름·소속으로 찾기": "Find by name or place",
 "이름순": "By name",
 "이미 보충자료 {0}개가 있습니다": "It already has {0} supplementary files",
 "이미 있음 {0} · 식별자 없음 {1}\n": "already held {0} · no identifier {1}\n",
 "이미지 주석 표시": "Show image annotations",
 "이스라엘": "Israel",
 "이어진 논문 {0} · 인용 {1}건 · 공통 참고문헌 쌍 {2}": "{0} papers linked · {1} citations · {2} pairs sharing references",
 "이전": "Previous",
 "이전 값을 적용했습니다. 새 입력은 아직 적용하지 않았습니다.": "The previous value was applied. The new input has not been.",
 "이전 페이지": "Previous page",
 "이전 플러그인이 노트에 남긴 읽기 시간을 찾아 옮깁니다.": "Finds the reading times an earlier plugin left in notes and moves them over.",
 "이탈리아": "Italy",
 "인도": "India",
 "인용 {0}": "{0} citations",
 "인용 가능 항목": "Citable items",
 "인용 관계": "Citations",
 "인용 관계 그래프": "Citation map",
 "인용 많은 순": "Most cited",
 "인용 목록 {0}/{1}": "References {0}/{1}",
 "인용 목록 가져오기 · OpenAlex ({0}편 남음)": "Fetch reference lists · OpenAlex ({0} left)",
 "인용 목록 없음": "No reference list",
 "인용 목록 없음 {0}": "{0} without a reference list",
 "인용 목록: {0}편 · 참고문헌 {1}건": "Reference lists: {0} papers · {1} references",
 "인용 목록·소속": "References and affiliations",
 "인용 수": "Citations",
 "인용 수 · {0}": "Citations · {0}",
 "인용 수 · 출처 미확인": "Citations · source unknown",
 "인용 수 열·자동 조회 사용": "Enable the Citations column and automatic lookup",
 "인용 수 저장 {0}개 · 확인 불가 {1}개": "Citations saved {0} · unavailable {1}",
 "인용 수 저장 {0}개 · 확인 불가 {1}개 · 중지됨": "Citations saved {0} · unavailable {1} · stopped",
 "인용 수 조회 중": "Looking up citations",
 "인용 수 조회 중지": "Stop looking up citations",
 "인용 수 조회를 중지했습니다. 지금까지 받은 값은 저장했습니다.": "Stopped the citation lookup. What was received is saved.",
 "인용 수 확인 {0}개 · 미확인 {1}개 · 식별자 부족 {2}개 · 조회 오류 {3}개{4}": "{0} citation counts checked · {1} unchecked · {2} without enough identifying information · {3} lookup errors{4}",
 "인용 수·IF": "Citations and IF",
 "인용 수·저널 정보": "Citation counts and journal facts",
 "인용 수를 Extra 필드에 'Citations: N (출처, 날짜)' 한 줄로 기록합니다. 원하지 않으면 설정 → Style Custom → 인용 수·IF → '논문 추가·수정 시 인용 수 조회 후 Extra 저장'을 끄세요.": "Citation counts are written into the Extra field as one line, 'Citations: N (source, date)'. To stop this, turn off Settings → Style Custom → Citations · IF → 'Look up citations on add/modify and save to Extra'.",
 "인용 조회: {0}": "Citation lookup: {0}",
 "인용 텍스트 표시": "Show quoted text",
 "인용…": "Cite…",
 "인용문을 만들 정보가 모자랍니다. 저자·연도·제목을 채운 뒤 다시 실행하세요.": "There is not enough here to build a citation. Fill in the authors, year and title, then try again.",
 "인용한 논문 {0}/{1}": "Citing papers {0}/{1}",
 "인용한 논문 가져오기 ({0}편 남음)": "Fetch citing papers ({0} left)",
 "일 전": "d ago",
 "일반": "Other",
 "일본": "JP",
 "일치하는 기능이 없습니다.": "No feature matches.",
 "일치하는 논문의 인용 수를 찾지 못했습니다.": "No citation count was found for a matching paper.",
 "읽기": "Reading",
 "읽기 기록": "Reading history",
 "읽기 기록 {0}": "Reading record {0}",
 "읽기 기록 {0}편 · {1}시간을 가져왔습니다.\n이미 더 많이 기록된 {2}편은 그대로 두었습니다.": "Imported {1} hours of reading history across {0} items.\n{2} that already had more recorded were left alone.",
 "읽기 기록 가져오기": "Bring in reading history",
 "읽기 메모": "Reading note",
 "읽기 메모 열 사용": "Enable the Reading note column",
 "읽기 메모 제안": "Suggest reading note",
 "읽기 메모 지시문": "Reading note prompt",
 "읽기 상태": "Status",
 "읽기 상태 열 표시": "Show the Status column",
 "읽기 상태 필터": "Reading status",
 "읽기 시간 표시 형식": "Reading-time format",
 "읽기 시간(초)": "Reading time (s)",
 "읽기 시간·상태 연동 사용": "Link reading time to reading status",
 "읽기 시간·페이지 진행 열 표시": "Show the reading time and page progress columns",
 "읽기 시간순": "Most read",
 "읽기 시작 시 reading 상태 자동 반영": "Set the status to reading when reading starts",
 "읽기 진행": "Reading progress",
 "읽기 진행 / PDF Style 도구": "Reading progress / PDF style tools",
 "읽기 진행 / PDF Style 도구 · 복원은 Custom이 추적한 원래 테마·사이드바 적용": "Reading progress / PDF style tools · restoring applies the original theme and sidebar that Custom tracked",
 "읽기 진행 / PDF Style 도구 · 왼쪽/오른쪽, 너비160–480px, 발췌100–5000자": "Reading progress / PDF style tools · left or right, 160–480px wide, 100–5000 characters of excerpt",
 "읽기 진행 → 색상 이름": "Reading → colour names",
 "읽는 문헌의 수정일 갱신": "Update Modified while reading",
 "읽는 중": "reading",
 "읽은 시간": "Time read",
 "읽은 시간 {0} · 아직 페이지 기록 없음": "Read {0} · no page record yet",
 "읽은 시간 {0} · 전체 {1}쪽 중 {2}쪽": "Read {0} · {2} of {1} pages",
 "읽은 시간과 페이지는 PDF를 열어 읽는 동안 자동으로 기록됩니다. 아직 기록이 없습니다.": "Reading time and pages are recorded automatically while a PDF is open. Nothing recorded yet.",
 "읽음": "read",
 "읽음·안 읽음 제목 구분 사용": "Distinguish read and unread titles",
 "입력한 값이 너무 깁니다. 짧게 줄여서 다시 저장하세요.": "That value is too long. Shorten it and save again.",
 "자동 (Zotero 설정을 따름) / Auto": "Auto (follow Zotero) / 자동",
 "자동은 Zotero 자체 언어를 따릅니다. English follows Zotero's own language when set to Auto.": "Auto follows Zotero's own language. 자동으로 두면 Zotero 언어 설정을 따릅니다.",
 "자세히": "Details",
 "작업 메뉴 표시": "Show the action menu",
 "작업 메뉴 표시·숨김 사용": "Enable showing and hiding the action menu",
 "작업 메뉴와 패널 디자인을 조절합니다.": "Adjust the action menu and the panel's design.",
 "작업 종류": "Action",
 "작업 패널 검색": "Search the panel",
 "작업 패널 닫기": "Close the panel",
 "작업 패널 하단 · 같은 라이브러리 문헌; 다른 문헌의 연결 보존": "At the foot of the panel · items in the same library; other items' links are kept",
 "잡지 기사": "Magazine article",
 "저널": "Journal",
 "저널 IF 공식 값 새로고침": "Refresh the journal impact factor",
 "저널 {0}종 · JIF 있는 저널 {1} · 분야 알려진 저널 {2}": "{0} journals · {1} with a JIF · {2} with a known field",
 "저널 {0}종 중 {1}종 지표 확인 · {2}종은 OpenAlex에도 없음": "{1} of {0} journals have a metric · {2} are not in OpenAlex either",
 "저널 검색": "Search journals",
 "저널 논문 검색을 열 수 없습니다. 도구 → 부가 기능에서 ZotPoP를 설치·활성화한 뒤 다시 시도하세요.": "The journal paper search cannot open. Install and enable ZotPoP under Tools → Add-ons, then try again.",
 "저널 등급 조회를 마쳤습니다.": "The journal rank lookup has finished.",
 "저널 등급 태그·조회 사용": "Enable journal-rank tags and lookup",
 "저널 등급을 조회하지 못했습니다. API 키와 연결을 확인하세요.": "The journal rank could not be looked up. Check the API key and the connection.",
 "저널 범위": "Which journals",
 "저널 수": "Journals",
 "저널 영향력 지수": "Journal impact factor",
 "저널 정렬": "Sort journals",
 "저널 정보가 없습니다.": "No journal information.",
 "저널 정보가 없습니다. 프리프린트·책·데이터셋에는 저널 IF가 적용되지 않을 수 있습니다.": "There is no journal information. A journal IF may not apply to a preprint, a book or a dataset.",
 "저널 지표": "Journal metrics",
 "저널 지표: {0}종 확인 · {1}종은 OpenAlex에도 없음": "Journal metrics: {0} checked · {1} not in OpenAlex either",
 "저널 지표를 조회합니다. 저널마다 한 번만 조회하고 결과는 보관합니다.": "Looks up journal metrics. Each journal is asked about once and the answer is kept.",
 "저널·발행처 열 사용": "Enable the Journal and Publisher columns",
 "저널·약어·출판사·분야 검색": "Search journals by name, abbreviation, publisher or field",
 "저널명": "Journal name",
 "저널명·약어·ISSN 검색": "Search by journal name, abbreviation or ISSN",
 "저널별 색": "Colour by journal",
 "저널이 있는 문헌이 없습니다.": "No items here name a journal.",
 "저자": "Authors",
 "저자 {0}명. 이름을 눌러 최근 작업을 확인하세요.": "{0} authors. Click a name to see their recent work.",
 "저자 사진 찾기": "Find author photos",
 "저자 식별자가 올바르지 않습니다. 관심 저자 목록에서 저자를 다시 고르세요.": "That author identifier is not valid. Pick the author again from the followed-authors list.",
 "저자 정보를 확인하는 중…": "Looking up the author…",
 "저자 추적": "Authors",
 "저자·기여자 열 사용": "Enable the Creators column",
 "저자로 이동": "Go to author",
 "저장 Q": "Stored Q",
 "저장 Q 순 (카테고리 미확인)": "By stored Q (category unverified)",
 "저장 Q는 원본 카테고리가 확인되지 않은 값입니다. CAS 등 추가 등급 조회는 easyScholar 키(선택)가 필요합니다.": "The stored Q is a source value whose category is unverified. Further grades such as CAS need an easyScholar key (optional).",
 "저장 위치: {0}": "Stored at: {0}",
 "저장 저널 {0}": "Stored journals {0}",
 "저장 저널 {0}종 · OpenAlex 분야 있음 {1} · 내 서재 {2}": "{0} stored journals · {1} with an OpenAlex subject · {2} in my library",
 "저장된 JIF 자료": "Stored JIF data",
 "저장된 OpenAlex 분야 정보가 없습니다.": "No stored OpenAlex subject for this journal.",
 "저장된 Q{0} · 카테고리 미확인": "Stored Q{0} · category unverified",
 "저장된 값을 다시 읽어 열을 새로 그립니다. 네트워크는 쓰지 않습니다.": "Redraws the columns from what is already saved. Nothing is fetched.",
 "저장된 날짜": "Stored date",
 "저장된 목록에 없음": "Not in the stored list",
 "저장된 목록에서 {0}번째 (JIF 순, 공식 JCR 순위 아님)": "{0} in the stored list (by JIF, not an official JCR rank)",
 "저장된 목록의 JIF 순번 · 공식 JCR 카테고리 순위 아님": "Position by JIF in the stored list · not an official JCR category rank",
 "저장된 뷰 그룹 이름": "Saved view group name",
 "저장된 주석 팔레트": "Saved palettes",
 "저장된 탭 그룹": "Saved tab groups",
 "저장된 탭 그룹 이름": "Saved tab group name",
 "저장하지 못했습니다. 디스크 공간과 Zotero 폴더 권한을 확인하세요. 지금까지의 기록은 창을 닫기 전까지 남아 있습니다.": "Could not save. Check the disk space and the permissions on your Zotero folder. What you have done so far is held until this window closes.",
 "저장한 노트 열기": "Open the saved note",
 "적게": "Less",
 "적용": "Apply",
 "적용 중인 필터": "Active filters",
 "적용하는 중…": "Applying…",
 "적용하지 못했습니다: {0}": "Could not apply: {0}",
 "적용했습니다.": "Applied.",
 "전면 OA": "Fully open access",
 "전체": "All",
 "전체 {0}개 · {1}/{2} 페이지 · CSV는 전체 문헌": "{0} in all · page {1}/{2} · the CSV holds every item",
 "전체 · {0}개": "All · {0}",
 "전체 내용 보기": "Show the whole thing",
 "전체 목록으로": "Back to the whole list",
 "전체 저널 목록 수집 미완료": "full journal list not yet captured",
 "전체 카테고리": "All categories",
 "전체 화면": "Fill the window",
 "전체 화면 전환": "Toggle full window",
 "접두사와 일치하는 태그": "Tags matching a prefix",
 "정렬": "Sort",
 "정렬 방향 바꾸기": "Reverse the sort order",
 "정리": "Organise",
 "정리할 별 태그가 없습니다.": "There are no star tags to tidy.",
 "정말 해제": "Really unfollow",
 "정정": "Corrected",
 "정정·정오표가 게시된 논문입니다.": "A correction or erratum has been published for this paper.",
 "제1저자": "First author",
 "제목": "Title",
 "제목 번역": "Translate title",
 "제목 앞 별 태그 정리": "Tidy star tags in titles",
 "제목 없는 노트": "Untitled note",
 "제목 없음": "Untitled",
 "제목 옆 색상·별점 태그": "Colour and rating tags beside the title",
 "제목 옆 최대 태그 수": "Maximum tags beside the title",
 "제목 옆 태그 표시": "Show tags beside the title",
 "제목 읽기 히트맵": "Title reading heat map",
 "제목 히트맵·태그·강조 사용": "Enable title heat maps, tags and highlighting",
 "제목·저자·태그 검색": "Search titles, authors and tags",
 "제목순": "By title",
 "제목에 읽기 히트맵 표시": "Show a reading heat map on titles",
 "제목으로 판별": "judged by the title",
 "제한 없음": "no limit",
 "조건에 맞는 문헌이 없습니다. 검색어나 필터를 지우세요. 새 논문을 찾으려면 ZotPoP 논문 검색을 사용하세요.": "No item matches. Clear the search or the filters. To find new papers, use ZotPoP's paper search.",
 "조건에 맞는 주석이 없습니다. PDF에서 하이라이트나 메모를 추가하세요.": "No annotation matches. Add a highlight or a note in the PDF.",
 "조회": "lookup",
 "조회 실패: 기존 값은 유지됩니다.": "The lookup failed; the existing value is kept.",
 "조회 오류 재시도 간격 (분)": "Retry interval after a failed lookup (minutes)",
 "조회 중": "Looking up",
 "조회처": "Source",
 "조회한 논문 {0} · 참고문헌 있는 논문 {1} · 참고문헌 {2}건": "{0} papers looked up · {1} with a reference list · {2} references",
 "종류 미판별 첨부 {0}편": "{0} with unjudged attachments",
 "주석": "Annotations",
 "주석 {0}": "Annotation {0}",
 "주석 {0}개": "{0} annotations",
 "주석 {0}개 · {1}개 페이지에 분포{2}. 색 막대를 클릭하면 해당 PDF 페이지로 이동합니다.": "{0} annotations across {1} pages{2}. Click a colour bar to jump to that page of the PDF.",
 "주석 검색": "Search annotations",
 "주석 관리·범위 선택·색상 일괄 변경·노트 추출 사용": "Enable managing annotations, choosing a scope, recolouring in bulk and extracting notes",
 "주석 메모 표시": "Show annotation comments",
 "주석 병합 기능이 꺼져 있습니다. 설정 → Style Custom → 리더에서 켜세요.": "Merging annotations is turned off. Turn it on under Settings → Style Custom → Reader.",
 "주석 본문·메모 검색": "Search annotation text and notes",
 "주석 색상": "Annotation colour",
 "주석 색상 기능이 꺼져 있습니다. 설정 → Style Custom → 리더에서 켜세요.": "Annotation colours are turned off. Turn them on under Settings → Style Custom → Reader.",
 "주석 색상 이름 사용": "Enable annotation colour names",
 "주석 색상·팔레트 사용": "Enable annotation colours and palettes",
 "주석 수·페이지별 색상 분포·원문 이동 사용": "Enable annotation counts, per-page colour spread and jumping to the source",
 "주석 원문 열기": "Open the annotation",
 "주석 위치 분포": "Where the annotations are",
 "주석 탭에 한 번에 그릴 개수": "Annotations drawn at once",
 "주석 텍스트보다 메모를 우선 표시": "Show the comment before the quoted text",
 "주석 팔레트 삭제": "Delete palette",
 "주석 팔레트 색상과 이름": "Palette colours and names",
 "주석 팔레트 선택": "Choose a palette",
 "주석 팔레트 이름": "Palette name",
 "주석 팔레트 저장": "Save palette",
 "주석 팔레트 적용": "Apply palette",
 "주석 팔레트를 선택하세요.": "Choose an annotation palette.",
 "주석 팔레트를 적용했습니다.": "The palette was applied.",
 "주석별 참조 노트 수·역링크 사용": "Enable per-annotation linked-note counts and backlinks",
 "주석을 눌러 선택하세요": "Select annotations to act on",
 "주석을 병합했습니다. 나머지 주석은 휴지통에서 복원할 수 있습니다.": "The annotations were merged. The rest can be restored from the trash.",
 "주석이 아닌 항목입니다. 주석을 고른 뒤 다시 실행하세요.": "That is not an annotation. Select an annotation and run this again.",
 "주장·논리 흐름·논쟁 여지": "Claims, lines of argument, points of contention",
 "주제가 가까운 논문": "Papers on a close subject",
 "주제가 맞는 관련 논문을 찾지 못했습니다.": "No related paper on a matching subject was found.",
 "준비": "Ready",
 "중국": "CN",
 "중복": "Duplicate",
 "중복 {0}개": "{0} duplicate",
 "중복 ×{0}": "dup ×{0}",
 "중복 첨부를 휴지통으로 보냈습니다. Zotero에서 되돌릴 수 있습니다.": "The duplicate attachment was moved to the trash. Zotero can undo this.",
 "중복×{0}": "dup×{0}",
 "중상위": "Upper",
 "중심성 {0}%": "centrality {0}%",
 "중위": "Mid",
 "중지했습니다.": "Stopped.",
 "중첩 태그": "Nested tags",
 "중첩 태그 탐색 사용": "Enable nested tag browsing",
 "즐겨찾기": "Favourites",
 "즐겨찾기 먼저": "Favourites first",
 "지금 채우기": "Fill now",
 "지표 없는 저널 {0}종": "{0} journals with no metric",
 "지표 연도": "Metric year",
 "지표 조회": "Look up metrics",
 "지표·읽기 기록 새로고침": "Refresh figures and reading time",
 "진행 중인 인용 수 조회가 없습니다. 중지할 것이 없습니다.": "No citation lookup is running, so there is nothing to stop.",
 "진행 중인 적용이 끝난 뒤 기본값으로 되돌리세요.": "Wait for the change in progress to finish, then restore the default.",
 "짧게 적어두세요. 노트 항목은 만들지 않습니다.": "Jot something short. No note item is created.",
 "참/거짓 값을 선택하세요.": "Choose true or false.",
 "참고문헌 {0}": "{0} references",
 "참고문헌 {0}건": "{0} references",
 "참고문헌을 많이 공유하거나 OpenAlex가 주제를 가깝게 본 논문 — 옆 연구": "Papers sharing many references, or that OpenAlex places close in topic — work alongside",
 "참조 노트": "Linked notes",
 "참조 노트 {0}개": "{0} linked notes",
 "참조 노트 보기": "Show linked notes",
 "창으로 띄우기": "Float as a window",
 "찾는 저자가 없습니다.": "No author matches.",
 "찾을 기능 이름": "Feature name",
 "채우기를 중지했습니다. 지금까지 받은 값은 저장했습니다.": "Filling was stopped. What arrived so far has been saved.",
 "책": "Book",
 "책의 장": "Book chapter",
 "책임저자": "senior author",
 "책임저자는 문헌 하나에서 찾습니다. 문헌을 하나만 선택하세요.": "The senior author is read from one paper. Select a single item.",
 "처음 여셨네요. 왼쪽 탭이 기능이고, ⌘/Ctrl K로 기능을 찾습니다. 문헌은 목록에서 고른 뒤 「현재 선택 가져오기」로 넘기고, 열 경계를 두 번 클릭하면 너비가 내용에 맞춰집니다.": "First time here. The tabs on the left are the features; ⌘/Ctrl K finds one. Pick papers in the list, then “Bring current selection”; double-click a column edge to fit its width.",
 "처음 펼칠 노트·주석 수": "Notes and annotations shown first",
 "처음 함께 낸 저자 {0}": "First-time co-authors {0}",
 "철회": "Retracted",
 "철회 신호·저널 지표·관심 저자의 새 논문을 한 번에 채웁니다.": "Fills retraction signals, journal figures and new papers by followed authors in one pass.",
 "철회 여부 미확인 {0}편": "{0} unchecked for retraction",
 "철회·공개접근 신호": "Retraction and open-access signals",
 "철회·공개접근 신호: {0}편 확인": "Retraction and open-access signals: {0} checked",
 "철회·공개접근 신호: 더 확인할 문헌이 없습니다.": "Retraction and open-access signals: there is nothing left to check.",
 "철회·공개접근 신호를 아직 조회하지 않았습니다. 문헌 목록 오른쪽 클릭 메뉴에서 조회하세요.": "Retraction and open-access signals have not been looked up. Use the right-click menu in the item list.",
 "철회·공개접근 확인": "Check retraction and open access",
 "철회된 논문입니다. 인용하기 전에 철회 사유를 확인하세요.": "This paper has been retracted. Check why before citing it.",
 "첨부 {0} · {1}페이지 · 주석 {2}개": "{0} · {1} pages · {2} annotations",
 "첨부 미리보기": "Attachments",
 "첨부 미리보기 사용": "Enable attachment preview",
 "첨부된 문서가 이 문헌의 제목을 전혀 쓰지 않습니다 — 클릭해서 확인하세요": "The attached document never uses this item's title — click to check",
 "첨부파일": "Attachment",
 "첨부파일 없음": "No attachment",
 "첨부파일 종류": "Attachment kinds",
 "첨부파일 종류 판별": "Sort out attachment kinds",
 "첨부파일 판별 중 {0}/{1}": "Judging attachments {0}/{1}",
 "첨부파일: 본문 {0} · 보충자료 {1}": "Attachments: article {0} · supplementary {1}",
 "첨부파일에 붙어 있던 평점 {0}개를 정리했습니다({1}개는 본 문헌으로 옮김).": "Tidied {0} ratings that were attached to files ({1} moved to the parent item).",
 "첨부파일을 선택하세요.": "Select an attachment.",
 "첨부파일이 없습니다. PDF 또는 스냅샷을 첨부하세요.": "There is no attachment. Attach a PDF or a snapshot.",
 "첫 문헌 아래에 노트로 저장했습니다.": "Saved as a note under the first paper.",
 "첫 문헌의 노트로 저장": "Save as a note on the first paper",
 "첫 페이지만으로는 종류를 판단하지 못한 파일입니다.": "The first page alone was not enough to tell what this file is.",
 "초": "s",
 "초록": "Abstract",
 "초록 요약": "Summarise abstract",
 "초록 요약 사용": "Enable abstract summaries",
 "초록이 없는 문헌이 있습니다: {0}": "Some items have no abstract: {0}",
 "초록이 없습니다.": "No abstract.",
 "총 인용": "Total citations",
 "최근 논문": "Recent papers",
 "최근 논문 {0}": "Recent papers {0}",
 "최근 논문을 찾지 못했습니다.": "No recent papers were found.",
 "최근 등록 순": "Most recently followed",
 "최근 문헌": "Recent",
 "최근 문헌 사용": "Enable Recent items",
 "최상위": "Top",
 "최소 별점": "Minimum rating",
 "최신 발행순": "Newest first",
 "추가": "Add",
 "추가 OpenAlex 프로필은 「빈 칸 채우기」로 조회할 수 있습니다. 저장된 분류는 표와 상세에서 동일하게 표시됩니다.": "More OpenAlex profiles can be fetched with “Fill the gaps”. The stored classification shows the same way in the table and the detail.",
 "추가 문헌 열": "Extra item columns",
 "추가 열 적용": "Apply extra columns",
 "추가 열을 적용했습니다.": "The extra columns were applied.",
 "추가 필드 열": "Extra field columns",
 "추가·제거할 정확한 태그 (쉼표로 구분)": "Exact tags to add or remove (comma separated)",
 "추가일·수정일 열 사용": "Enable Added and Modified columns",
 "추가할 태그": "Tags to add",
 "추가했습니다 — {0}": "Added — {0}",
 "축소": "Zoom out",
 "출력 언어": "Output language",
 "출원 {0}": "filed {0}",
 "출처 링크가 포함된 노트를 만들었습니다.": "A note with source links was created.",
 "출판 3년 이내 ({0}) — 아직 인용이 쌓이는 중이라 회색 · 길이는 로그 눈금": "Published within the last three years ({0}) — grey because citations are still accumulating · length is on a log scale",
 "출판사": "Publisher",
 "출판사의 보충자료 파일로 내려받았습니다": "Downloaded from the publisher's supplementary files",
 "카드 메모": "Card note",
 "카드 모양 저장": "Save card layout",
 "카드 색상": "Card colour",
 "카드 색상은 #RRGGBB 형식으로 적으세요.": "Write the card colour as #RRGGBB.",
 "카드 선택": "Select card",
 "카드 연결": "Link cards",
 "카드 연결 해제": "Unlink cards",
 "카드 제목": "Card title",
 "카드 제목을 입력하세요.": "Enter a card title.",
 "카드 편집": "Edit card",
 "카드·보드 이름·색상·연결 편집과 삭제 복원 사용": "Enable editing card and board names, colours and links, and undoing a delete",
 "카드로 보기": "As cards",
 "카드를 찾지 못했습니다. 보드를 새로 고친 뒤 다시 시도하세요.": "That card is gone. Refresh the board and try again.",
 "카테고리": "Category",
 "카테고리 그룹": "Category groups",
 "카테고리 미확인 · 공식 카테고리별 사분위로 사용할 수 없습니다": "Category unverified · cannot serve as an official per-category quartile",
 "카테고리 수": "Categories",
 "카테고리 안에서 저널 검색": "Search journals within the category",
 "캐나다": "Canada",
 "캔버스": "Canvas",
 "캔버스 선택": "Choose canvas",
 "커스텀 열로 전환": "Switch to custom columns",
 "컬렉션": "Collections",
 "컬렉션 {0}개 · 문헌 {1}편 · 빈 컬렉션 {2}개": "{0} collections · {1} papers · {2} empty",
 "컬렉션 검색": "Search collections",
 "컬렉션 문헌 수 사용": "Enable collection counts",
 "컬렉션 열기": "Open collection",
 "컬렉션 이름 검색": "Search collections by name",
 "컬렉션 이름·개수·즐겨찾기 정렬 사용": "Enable sorting collections by name, count and favourite",
 "컬렉션 정렬": "Sort collections",
 "컬렉션 즐겨찾기 사용": "Enable collection favourites",
 "컬렉션이 없습니다.": "No collections.",
 "켜짐": "on",
 "클립보드에 복사했습니다.": "Copied to the clipboard.",
 "탐색": "Explore",
 "태그": "Tags",
 "태그 목록으로 읽을 수 없는 답이 왔습니다. 다시 시도하세요.": "The answer could not be read as a list of tags. Try again.",
 "태그 변경 {0}개 문헌 · 병합 {1}개": "{0} items retagged · {1} merged",
 "태그 열 표시 대상": "Which tags the column shows",
 "태그 제안": "Suggest tags",
 "태그 제안 지시문": "Tag suggestion prompt",
 "태그 추가·제거·경로 이름 변경·병합 사용": "Enable adding, removing, renaming and merging tags",
 "태그 표시 방식과 제목 옆 태그를 조절합니다.": "Controls how tags are shown and which appear beside the title.",
 "태그 필터 해제": "Clear tag filter",
 "태그가 없습니다. 문헌을 선택하고 태그를 추가하세요.": "There are no tags. Select items and add some.",
 "태그로 남은 평점이 없습니다.": "No ratings are left as tags.",
 "탭 관리": "Tabs",
 "탭 관리 / PDF Style 도구": "Tabs / PDF style tools",
 "탭 그룹 이름": "Tab group name",
 "탭 그룹 이름 변경": "Rename tab group",
 "탭 뒤로": "Tab back",
 "탭 순서·다른 탭 닫기·저장 그룹 편집 사용": "Enable tab ordering, closing others and editing saved groups",
 "탭 앞으로": "Tab forward",
 "탭 활동 시 수정일 갱신 사용": "Update Modified when a tab is used",
 "탭으로 열기": "Open in a tab",
 "탭으로 열기 / 창으로 띄우기": "Open in a tab / float as a window",
 "텍스트": "Text",
 "텍스트 주석 표시": "Show text annotations",
 "텍스트 태그 접두사": "Text tag prefix",
 "텍스트 태그·태그 수 사용": "Enable text tags and tag counts",
 "특허": "Patent",
 "특허 {0}": "Patents {0}",
 "특허 {0} · 새 {1}": "Patents {0} · new {1}",
 "특허 확인은 설정에 USPTO Open Data Portal 키를 넣으면 켜집니다 (무료).": "The patent check turns on once a USPTO Open Data Portal key is entered in Settings (free).",
 "파일 열기": "Open file",
 "파일 이름으로 판별": "judged by the file name",
 "패널 CSS 적용": "Apply panel CSS",
 "패널 CSS 편집 사용": "Enable panel CSS editing",
 "패널 글꼴 크기": "Panel font size",
 "패널 글자 크기": "Panel font size",
 "패널 범위에만 적용됩니다. 외부 파일을 불러오는 CSS는 허용하지 않습니다.": "Applies only within the panel. CSS that loads external files is not allowed.",
 "페이지당": "Per page",
 "페이지당 표시 수": "Rows per page",
 "펜 주석 표시": "Show ink annotations",
 "평점 태그를 Extra로 옮기기": "Move rating tags into Extra",
 "폴란드": "Poland",
 "표시": "Show",
 "표시 결과": "shown",
 "표시 범위": "Scope",
 "표와 필터에 사용하는 동일한 OpenAlex 분류 경로": "The same OpenAlex classification path the table and filters use",
 "표준": "Standard",
 "프랑스": "France",
 "프로필 펼치기·접기": "Open or close the profile",
 "프리프린트": "Preprint",
 "프리프린트입니다. 정식 게재본은 찾지 못했습니다.": "This is a preprint; no formally published version was found.",
 "플러그인이 꺼져 있습니다. 도구 → 부가 기능에서 Style Custom을 켜세요.": "The plugin is turned off. Turn Style Custom on under Tools → Add-ons.",
 "피인용 수 · 길이는 로그 눈금": "Citation count · length is on a log scale",
 "핀란드": "Finland",
 "필기": "Ink",
 "필터 초기화": "Reset filters",
 "하위 {0}": "{0} inside",
 "하위 태그도 변경": "Rename child tags too",
 "하이라이트": "Highlight",
 "하이라이트 표시": "Show highlights",
 "학위논문": "Thesis",
 "학회 논문": "Conference paper",
 "한 번에 20개 이하의 저널을 선택하세요.": "Select 20 journals or fewer at a time.",
 "한 번에 여섯 편까지 비교할 수 있습니다. 몇 편을 빼고 다시 실행하세요.": "Six papers at a time is the limit. Take some out and run it again.",
 "한 줄에 #RRGGBB 색상과 이름을 쉼표로 구분해 입력하세요.": "One line each: a #RRGGBB colour and a name, separated by a comma.",
 "한 페이지 문헌 수": "Items per page",
 "한국": "KR",
 "한국어": "Korean",
 "함께 낸 저자 {0}": "Co-authors {0}",
 "함께 읽기": "Read together",
 "함께 읽기 ({0})\n\n": "Read together ({0})\n\n",
 "함께 읽기 지시문 (선택)": "Read-together outline (optional)",
 "항목 아이콘 / 작업 패널 유형 필터": "Item icon / panel type filter",
 "항목 아이콘 클릭으로 유형 필터": "Filter by type by clicking the item icon",
 "항목 아이콘으로 유형 필터": "Filter by type from the item icon",
 "항목 유형": "item type",
 "항목 유형 빠른 필터 사용": "Enable the item-type quick filter",
 "항목별 설명을 확인하고 값을 적용하세요. 텍스트 입력은 적용을 눌러야 저장됩니다.": "Read each description and apply the value. Text fields are only saved when Apply is pressed.",
 "해제": "Unfollow",
 "행·열 전환": "Swap rows and columns",
 "현재 결과 밖 {0}개 포함": "including {0} outside the current results",
 "현재 동작": "Current behaviour",
 "현재 동작 상태": "Current state",
 "현재 동작 정보를 제공하지 않습니다.": "It does not report its current behaviour.",
 "현재 동작을 확인하지 못했습니다.": "The current behaviour could not be checked.",
 "현재 문헌의 결과를 먼저 생성하세요.": "Generate a result for this item first.",
 "현재 범위의 주석을 선택하세요.": "Select annotations within the current scope.",
 "현재 보드 이름": "Current board name",
 "현재 뷰 저장": "Save the current view",
 "현재 상태를 확인하는 중…": "Checking the current state…",
 "현재 선택 가져오기": "Take the current selection",
 "현재 선택 문헌 누적 읽기": "Total reading time for the selection",
 "현재 열 배치 이름": "Name for this column layout",
 "현재 열 배치로 뷰 갱신": "Update the view from the current columns",
 "현재 컬렉션": "Current collection",
 "현재 컬렉션과 하위 컬렉션": "Current collection and its subcollections",
 "현재 탭": "This tab",
 "현재 탭으로 그룹 갱신": "Update the group from the open tabs",
 "현재 페이지 선택": "Select this page",
 "현재 페이지 선택 해제": "Deselect this page",
 "현재·하위 컬렉션": "This collection and its subcollections",
 "호주": "Australia",
 "홈페이지": "Homepage",
 "홍콩": "Hong Kong",
 "화면 밀도": "Density",
 "화면 밀도 전환": "Toggle density",
 "확대": "Zoom in",
 "확인 {0} · 미확인 {1}": "checked {0} · unchecked {1}",
 "확인 가능한 논문 식별자가 부족합니다.": "There is not enough identifying information.",
 "확인 안 한 관심 저자 {0}명": "{0} followed authors not checked",
 "확인한 결과를 저장했습니다.": "The result you checked was saved.",
 "활성 PDF 읽기 시간 기록": "Record reading time for the active PDF",
 "후보가 둘입니다 — 직접 고르세요: {0}": "There are two candidates — choose one: {0}",
 "휴지통으로": "Move to trash"
};
  const api = {en};
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  root.CustomStyleStrings = api;
})(typeof globalThis !== 'undefined' ? globalThis : this);
