import test from 'node:test';import assert from 'node:assert/strict';import A from '../src/assist.js';
function harness(values={}){const prefs={aiEndpoint:'https://example.org/v1/chat/completions',aiModel:'configured-model',aiKey:'secret',...values};const requests=[];let response={status:200,response:{choices:[{message:{content:'Result'}}]}};const api=A.create({runtime:{pref:k=>prefs[k]},Zotero:{HTTP:{request:async(method,url,options)=>{requests.push({method,url,options});return typeof response==='function'?response(options):response;}}}});return{api,requests,prefs,respond:value=>response=value};}
test('assistance requires explicit endpoint/model, sends selected text only and avoids model-specific unsupported fields',async()=>{const h=harness();assert.equal(await h.api.run('summary',{title:'Title',abstract:'Evidence'}),'Result');const r=h.requests[0];assert.equal(r.method,'POST');assert.equal(r.options.headers.Authorization,'Bearer secret');const body=JSON.parse(r.options.body);assert.equal(body.model,'configured-model');assert.equal(body.store,false);assert.equal(body.messages[1].content,'{"title":"Title","abstract":"Evidence"}');assert.equal(body.temperature,undefined);assert.equal(r.options.successCodes,false);assert.equal(h.requests.length,1);await assert.rejects(h.api.run('summary',{title:'Title'}),/초록/);});
test('unconfigured/unsafe endpoints produce no requests, localhost services are supported',async()=>{for(const endpoint of ['', 'http://remote.test/api','https://user:pass@remote.test/api','javascript:alert(1)']){const h=harness({aiEndpoint:endpoint});await assert.rejects(h.api.run('translate',{title:'A title'}));assert.equal(h.requests.length,0);}assert.equal(A.endpoint('http://127.0.0.1:1234/v1/chat/completions'),'http://127.0.0.1:1234/v1/chat/completions');});
test('tag responses must be bounded plain strings, malformed model data cannot become mutations',async()=>{const h=harness();h.respond({status:200,response:{choices:[{message:{content:'["CRISPR","CRISPR","Thermophiles"]'}}]}});assert.deepEqual(await h.api.run('tags',{title:'T',abstract:'A'}),['CRISPR','Thermophiles']);h.respond({status:200,response:{choices:[{message:{content:'[{"code":"bad"}]'}}]}});await assert.rejects(h.api.run('tags',{title:'T',abstract:'A'}),/태그/);});
test('cancellation discards late output and stop prevents future calls',async()=>{const h=harness();let finish,cancelled=0;h.respond(options=>new Promise(resolve=>{finish=resolve;options.cancellerReceiver(()=>cancelled++);}));const promise=h.api.run('translate',{title:'T'});h.api.cancel();finish({status:200,response:{choices:[{message:{content:'Late'}}]}});await assert.rejects(promise,/중지/);assert.equal(cancelled,1);h.api.stop();await assert.rejects(h.api.run('translate',{title:'T'}),/비활성화/);});
test('HTTP failures and exceptions never echo credentials',async()=>{const h=harness();h.respond(()=>{throw Error('secret Authorization Bearer');});await assert.rejects(h.api.run('translate',{title:'T'}),e=>!e.message.includes('secret'));h.respond({status:401,response:{}});await assert.rejects(h.api.run('translate',{title:'T'}),/HTTP 401/);});
test('cancel settles immediately even when the HTTP transport never settles and canceller arrives late',async()=>{
 const h=harness();let deliver,cancelled=0;
 h.respond(options=>{deliver=()=>options.cancellerReceiver(()=>cancelled++);return new Promise(()=>{});});
 const running=h.api.run('translate',{title:'Pending'});h.api.cancel();
 const winner=await Promise.race([running.then(()=> 'resolved',e=>e.message),new Promise(resolve=>setTimeout(()=>resolve('timeout'),30))]);
 assert.notEqual(winner,'timeout');assert.match(winner,/중지/);deliver();assert.equal(cancelled,1);
 h.respond({status:200,response:{choices:[{message:{content:'Next'}}]}});assert.equal(await h.api.run('translate',{title:'Next'}),'Next');h.api.stop();
});
